import * as THREE from 'three';
export function createAtmosphere(){
 const uniforms={time:{value:0},tint:{value:new THREE.Color('#747c7c')}};
 const sky=new THREE.Mesh(new THREE.SphereGeometry(2100,32,20),new THREE.ShaderMaterial({side:THREE.BackSide,depthWrite:false,uniforms,vertexShader:`varying vec3 vP;void main(){vP=position;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.);}`,fragmentShader:`varying vec3 vP;uniform vec3 tint;uniform float time;
 float hash(vec2 p){return fract(sin(dot(p,vec2(127.1,311.7)))*43758.5453);}float noise(vec2 p){vec2 i=floor(p),f=fract(p);f=f*f*(3.-2.*f);return mix(mix(hash(i),hash(i+vec2(1,0)),f.x),mix(hash(i+vec2(0,1)),hash(i+1.),f.x),f.y);}float fbm(vec2 p){float n=0.,a=.5;for(int i=0;i<5;i++){n+=a*noise(p);p=p*2.03+17.;a*=.5;}return n;}
 void main(){vec3 d=normalize(vP);vec2 p=d.xz/max(.17,d.y+.35)*2.;float clouds=fbm(p+vec2(time*.003,0));float detail=fbm(p*3.-time*.004);vec3 color=mix(tint*.35,tint*1.2,smoothstep(.2,.83,clouds));color*=.83+detail*.35;float light=pow(max(dot(d,normalize(vec3(-.6,.35,-.4))),0.),18.);color+=vec3(.24,.2,.14)*light*(1.-clouds);color=mix(tint,color,smoothstep(-.03,.3,d.y));gl_FragColor=vec4(color,1.);#include <tonemapping_fragment>\n#include <colorspace_fragment>}`.replace(';#include',';\n#include')}));sky.frustumCulled=false;
 const cv=document.createElement('canvas');cv.width=cv.height=64;const cx=cv.getContext('2d'),gr=cx.createRadialGradient(32,32,0,32,32,32);gr.addColorStop(0,'#777');gr.addColorStop(.4,'#444');gr.addColorStop(1,'#000');cx.fillStyle=gr;cx.fillRect(0,0,64,64);const positions=new Float32Array(80*3),geo=new THREE.BufferGeometry();geo.setAttribute('position',new THREE.BufferAttribute(positions,3));const mat=new THREE.PointsMaterial({color:0xacb6aa,size:24,transparent:true,opacity:.12,alphaMap:new THREE.CanvasTexture(cv),depthWrite:false,sizeAttenuation:true});const mist=new THREE.Points(geo,mat);mist.frustumCulled=false;
 return{sky,mist,update(t,player,color,sector){uniforms.time.value=t;uniforms.tint.value.copy(color);sky.position.set(player.x,0,player.z);mat.opacity=sector===1?.14:sector===3?.18:.055;mat.color.copy(color).lerp(new THREE.Color('#ddd5bb'),.2);for(let i=0;i<80;i++){const a=i*2.399,r=30+(i%13)*19;positions[i*3]=player.x+Math.sin(a+t*.015)*r;positions[i*3+1]=sector===3?3+(i%9)*3+Math.sin(t*.4+i)*2:1+(i%5)*1.2;positions[i*3+2]=player.z+Math.cos(a+t*.015)*r;}geo.attributes.position.needsUpdate=true;}};
}
export function createReflection(renderer,water,mobile){
 const target=new THREE.WebGLRenderTarget(mobile?384:640,mobile?256:384,{type:THREE.HalfFloatType,depthBuffer:true});
 const mirror=new THREE.PerspectiveCamera(),matrix=new THREE.Matrix4(),bias=new THREE.Matrix4().set(.5,0,0,.5,0,.5,0,.5,0,0,.5,.5,0,0,0,1),direction=new THREE.Vector3(),look=new THREE.Vector3();let last=-1;
 water.uniforms.reflectionMap={value:target.texture};water.uniforms.reflectionMatrix={value:matrix};
 return{update(scene,camera,waterMesh,hidden,t){if(t-last<(mobile?1/24:1/36))return;last=t;camera.updateMatrixWorld();mirror.copy(camera);mirror.position.y=-camera.position.y;camera.getWorldDirection(direction);look.copy(camera.position).add(direction);look.y=-look.y;mirror.up.set(0,-1,0);mirror.lookAt(look);mirror.updateMatrixWorld();matrix.copy(bias).multiply(mirror.projectionMatrix).multiply(mirror.matrixWorldInverse);const oldTarget=renderer.getRenderTarget(),oldClip=renderer.clippingPlanes,oldShadow=renderer.shadowMap.autoUpdate;const objects=[waterMesh,...hidden],vis=objects.map(o=>o.visible);objects.forEach(o=>o.visible=false);renderer.shadowMap.autoUpdate=false;renderer.clippingPlanes=[new THREE.Plane(new THREE.Vector3(0,1,0),-.06)];renderer.setRenderTarget(target);renderer.clear();renderer.render(scene,mirror);renderer.setRenderTarget(oldTarget);renderer.clippingPlanes=oldClip;renderer.shadowMap.autoUpdate=oldShadow;objects.forEach((o,i)=>o.visible=vis[i]);}};
}
export function createLens(){
 const host=document.getElementById('lens'),drops=[];let t=0,last=-20;
 function splash(strength){last=t;for(let i=0;i<Math.ceil(5+strength*8);i++){if(drops.length>=26){drops.shift().el.remove();}const el=document.createElement('i'),size=8+Math.random()*35*strength,x=8+Math.random()*84,y=10+Math.random()*65;el.className='lens-drop';el.style.width=size+'px';el.style.height=size*(1.1+Math.random()*.55)+'px';el.style.left=x+'%';el.style.top=y+'%';el.style.transform=`rotate(${Math.random()*60-30}deg)`;host.appendChild(el);drops.push({el,age:0,life:1.5+Math.random()*3,y,speed:.3+Math.random()*1.2});}}
 return{get last(){return last;},get count(){return drops.length;},splash,clear(){drops.forEach(d=>d.el.remove());drops.length=0;last=-20;},update(dt,time,state){t=time;host.hidden=!['race','countdown'].includes(state);for(let i=drops.length-1;i>=0;i--){const d=drops[i];d.age+=dt;d.y+=dt*d.speed*(1+d.age);d.el.style.top=d.y+'%';d.el.style.opacity=Math.min(1,(d.life-d.age)*1.4)*.8;if(d.age>=d.life){d.el.remove();drops.splice(i,1);}}}};
}
