export class RaceAudio{
 constructor(){this.ctx=null;this.enabled=true;this.active=false;}
 async init(){if(this.ctx){await this.ctx.resume();return;}this.ctx=new (window.AudioContext||window.webkitAudioContext)();this.master=this.ctx.createGain();this.master.gain.value=this.enabled?.35:0;this.master.connect(this.ctx.destination);this.engineGain=this.ctx.createGain();this.engineGain.gain.value=0;const filter=this.ctx.createBiquadFilter();filter.type='lowpass';filter.frequency.value=650;this.filter=filter;filter.connect(this.engineGain);this.engineGain.connect(this.master);this.osc=this.ctx.createOscillator();this.osc.type='sawtooth';this.osc.frequency.value=42;this.osc.connect(filter);this.osc.start();this.sub=this.ctx.createOscillator();this.sub.type='triangle';this.sub.frequency.value=30;this.sub.connect(filter);this.sub.start();const buffer=this.ctx.createBuffer(1,this.ctx.sampleRate*2,this.ctx.sampleRate),data=buffer.getChannelData(0);let b=0;for(let i=0;i<data.length;i++){b=(b+(Math.random()*2-1)*.04)/1.02;data[i]=b*3.5;}const noise=this.ctx.createBufferSource();noise.buffer=buffer;noise.loop=true;this.splashGain=this.ctx.createGain();this.splashGain.gain.value=0;const hp=this.ctx.createBiquadFilter();hp.type='highpass';hp.frequency.value=950;noise.connect(hp);hp.connect(this.splashGain);this.splashGain.connect(this.master);noise.start();}
 setEnabled(v){this.enabled=v;if(this.master)this.master.gain.setTargetAtTime(v?.35:0,this.ctx.currentTime,.1);if(this.music)this.music.volume=v?.14:0;}
 update(speed,boost,running){if(!this.ctx)return;const t=this.ctx.currentTime;this.osc.frequency.setTargetAtTime(35+speed*2.4+(boost?18:0),t,.12);this.sub.frequency.setTargetAtTime(24+speed*.9,t,.15);this.filter.frequency.setTargetAtTime(220+speed*22+(boost?600:0),t,.15);this.engineGain.gain.setTargetAtTime(running?.12+speed*.002:0,t,.15);this.splashGain.gain.setTargetAtTime(running?Math.min(.45,speed*.009):0,t,.15);if(this.music)this.music.volume=this.enabled?(running?.15:.07):0;if(this.wash)this.wash.volume=this.enabled&&running?Math.min(.24,speed*.004):0;}
 tone(freq=660,duration=.18){if(!this.ctx||!this.enabled)return;const o=this.ctx.createOscillator(),g=this.ctx.createGain(),t=this.ctx.currentTime;o.type='sine';o.frequency.setValueAtTime(freq,t);o.frequency.exponentialRampToValueAtTime(freq*1.4,t+duration);g.gain.setValueAtTime(.1,t);g.gain.exponentialRampToValueAtTime(.001,t+duration);o.connect(g);g.connect(this.master);o.start();o.stop(t+duration);}
 weapon(type){if(!this.ctx||!this.enabled)return;const t=this.ctx.currentTime,o=this.ctx.createOscillator(),g=this.ctx.createGain();o.type=type==='LASER'?'sawtooth':'triangle';o.frequency.setValueAtTime(type==='IMPACT'?95:type==='LASER'?1200:320,t);o.frequency.exponentialRampToValueAtTime(type==='IMPACT'?25:80,t+.4);g.gain.setValueAtTime(.18,t);g.gain.exponentialRampToValueAtTime(.001,t+.5);o.connect(g);g.connect(this.master);o.start();o.stop(t+.5);}
 async loadMusic(url){this.wash=new Audio('./media/water-wash.mp3');this.wash.loop=true;this.wash.volume=0;this.wash.play().catch(()=>{});this.music=new Audio(url);this.music.loop=true;this.music.volume=.12;try{await this.music.play();}catch{}}
}
