export const CHAPTERS = [
 {name:'PORT MERIDIAN',short:'PORT\nMERIDIAN',tag:'THE DEPARTURE',story:'Your first clearance starts at the harbour. Earn a place on the podium.',objective:'Finish in the top three',radius:190,stretch:1.15,bend:.10,width:30,water:'#087e8b',deep:'#063d50',sky:'#adc8cd',fog:0.0016,sun:24,seed:11,kind:'harbour',waves:.24,par:52},
 {name:'DROWNED REACH',short:'DROWNED\nREACH',tag:'THE LOST SIGNAL',story:'Old signal buoys mark a forgotten passage. Recover four to open the gorge.',objective:'Collect 4 signal buoys and finish',radius:180,stretch:1.23,bend:.18,width:25,water:'#387865',deep:'#163f3c',sky:'#b3c5ae',fog:0.0032,sun:17,seed:32,kind:'swamp',waves:.13,par:57},
 {name:'SPLITSTONE PASSAGE',short:'SPLITSTONE\nPASSAGE',tag:'THE LEAP OF FAITH',story:'The island splits here. Land two ramp jumps to earn your passage.',objective:'Land 2 marked jumps and finish',radius:205,stretch:1.05,bend:.20,width:25,water:'#249db0',deep:'#0a4e64',sky:'#a6c8d4',fog:0.002,sun:32,seed:73,kind:'gorge',waves:.32,par:59},
 {name:'EMBER BASIN',short:'EMBER\nBASIN',tag:'FIRE BELOW',story:'Steam rises from the caldera. Claim a podium and prove your boost control.',objective:'Top three + use boost 3 times',radius:200,stretch:1.2,bend:.15,width:29,water:'#45787a',deep:'#173d4b',sky:'#b6a9a0',fog:0.0025,sun:12,seed:99,kind:'volcano',waves:.3,par:61},
 {name:'THE SLUICE',short:'THE\nSLUICE',tag:'BORROWED TIME',story:'The sea gates breathe on a timer. Catch two green surge windows.',objective:'Pass 2 active surge gates and finish',radius:195,stretch:1.3,bend:.14,width:29,water:'#257f8e',deep:'#103e51',sky:'#b7c4c3',fog:0.0018,sun:21,seed:148,kind:'sluice',waves:.38,par:61},
 {name:'OUTER ATLANTIC',short:'OUTER\nATLANTIC',tag:'BEYOND THE BREAKWATER',story:'All clearances earned. One final race. Bring the Atlantic crown home.',objective:'Win the Atlantic final',radius:235,stretch:1.05,bend:.15,width:34,water:'#367e92',deep:'#12394f',sky:'#8fa9ba',fog:0.0018,sun:14,seed:201,kind:'ocean',waves:.64,par:64},
];
export const BOATS=[{name:'KESTREL',width:4.54,type:'BALANCED / INTERCEPTOR',color:0xff653f,speed:38,turn:1.1,boost:1.48,stats:[.78,.83,.80]},{name:'ALBATROSS',width:4.35,type:'SPEED / NEEDLECRAFT',color:0xe5e3d7,speed:41,turn:.96,boost:1.55,stats:[.96,.64,.93]},{name:'MANTA',width:5.31,type:'AGILITY / WINGCRAFT',color:0x2dc3ca,speed:36,turn:1.3,boost:1.44,stats:[.69,.98,.74]}];
export function objectivePassed(chapter,run){if(!run.finished)return false;switch(chapter){case 0:return run.place<=3;case 1:return run.signals>=4;case 2:return run.jumps>=2;case 3:return run.place<=3&&run.boosts>=3;case 4:return run.surges>=2;case 5:return run.place===1;default:return false;}}
export function objectiveProgress(chapter,r){switch(chapter){case 0:return `PODIUM TARGET · ${r.place||6}/6`;case 1:return `SIGNALS RECOVERED · ${Math.min(4,r.signals)}/4`;case 2:return `JUMPS LANDED · ${Math.min(2,r.jumps)}/2`;case 3:return `BOOSTS · ${Math.min(3,r.boosts)}/3 · FINISH TOP 3`;case 4:return `SURGE WINDOWS · ${Math.min(2,r.surges)}/2`;case 5:return 'ATLANTIC FINAL · FINISH FIRST';}}
const KEY='tidebreak.campaign.v1';
export function loadSave(){try{const s=JSON.parse(localStorage.getItem(KEY));if(s&&Array.isArray(s.cleared)&&Array.isArray(s.best))return {cleared:Array.from({length:6},(_,i)=>s.cleared[i]===true),best:Array.from({length:6},(_,i)=>Number.isFinite(s.best[i])&&s.best[i]>0?s.best[i]:null),champion:s.champion===true};}catch{}return{cleared:Array(6).fill(false),best:Array(6).fill(null),champion:false};}
export function unlocked(save,i){return i===0||save.cleared.slice(0,i).every(Boolean);}
export function recordResult(save,i,run,mode){const next={...save,cleared:[...save.cleared],best:[...save.best]};if(run.finished){next.best[i]=Math.min(next.best[i]??Infinity,run.time);if(mode==='race'&&objectivePassed(i,run)){next.cleared[i]=true;if(i===5)next.champion=true;}}try{localStorage.setItem(KEY,JSON.stringify(next));}catch{}return next;}
export function formatTime(t){const ms=Math.max(0,Math.round(t*1000));return `${String(Math.floor(ms/60000)).padStart(2,'0')}:${String(Math.floor(ms/1000)%60).padStart(2,'0')}.${String(ms%1000).padStart(3,'0')}`;}
