import * as THREE from 'three';
import {ENGINE_COLORS,distance,lane,live} from './combat.js';
export function createCombatFX(scene){
 const group=new THREE.Group();scene.add(group);const meshes=new Map(),bursts=[];
 const rocketGeo=new THREE.ConeGeometry(.35,2.5,8).rotateX(Math.PI/2),mineGeo=new THREE.IcosahedronGeometry(1.05,0),ringGeo=new THREE.TorusGeometry(1,.06,4,32);
 const materials={MISSILE:new THREE.MeshBasicMaterial({color:0xffbd79}),SEEKER:new THREE.MeshBasicMaterial({color:0xc690ff}),LASER:new THREE.MeshBasicMaterial({color:0x70efff}),MINE:new THREE.MeshBasicMaterial({color:0xff4151}),BOMB:new THREE.MeshBasicMaterial({color:0xff985a})};
 const count=350,positions=new Float32Array(count*3),colors=new Float32Array(count*3),ages=new Float32Array(count).fill(9),velocities=new Float32Array(count*3);let cursor=0;
 const geo=new THREE.BufferGeometry();geo.setAttribute('position',new THREE.BufferAttribute(positions,3));geo.setAttribute('color',new THREE.BufferAttribute(colors,3));
 const cv=document.createElement('canvas');cv.width=cv.height=32;const ctx=cv.getContext('2d'),g=ctx.createRadialGradient(16,16,0,16,16,16);g.addColorStop(0,'#fff');g.addColorStop(.25,'#bbb');g.addColorStop(1,'#000');ctx.fillStyle=g;ctx.fillRect(0,0,32,32);
 const particles=new THREE.Points(geo,new THREE.PointsMaterial({size:1,vertexColors:true,transparent:true,opacity:.65,alphaMap:new THREE.CanvasTexture(cv),blending:THREE.AdditiveBlending,depthWrite:false}));particles.frustumCulled=false;group.add(particles);
 function emit(x,y,z,color,heading,speed){const i=cursor++%count,c=new THREE.Color(color);positions.set([x,y,z],i*3);colors.set([c.r,c.g,c.b],i*3);velocities.set([-Math.sin(heading)*speed+(Math.random()-.5)*3,Math.random()*2,-Math.cos(heading)*speed+(Math.random()-.5)*3],i*3);ages[i]=0;}
 function burst(s,offset,course){const o=new THREE.Mesh(new THREE.IcosahedronGeometry(1,1),new THREE.MeshBasicMaterial({color:0xffb269,transparent:true,opacity:.9,wireframe:true,depthWrite:false}));o.position.copy(course.at(s,offset).p);o.position.y=2;group.add(o);bursts.push({mesh:o,age:0});}
 return {group,burst,clear(){for(const o of meshes.values())group.remove(o);meshes.clear();for(const b of bursts){group.remove(b.mesh);b.mesh.geometry.dispose();b.mesh.material.dispose();}bursts.length=0;ages.fill(9);positions.fill(0);},update(dt,time,combat,racers,course,player){
  const ids=new Set(combat.shots.map(p=>p.id));for(const [id,o] of meshes)if(!ids.has(id)){group.remove(o);meshes.delete(id);}
  for(const p of combat.shots){let o=meshes.get(p.id);if(!o){o=new THREE.Group();const m=new THREE.Mesh(['MINE','BOMB'].includes(p.type)?mineGeo:rocketGeo,materials[p.type]);o.add(m);if(['MINE','BOMB'].includes(p.type)){const ring=new THREE.Mesh(ringGeo,materials[p.type]);ring.rotation.x=-Math.PI/2;ring.scale.setScalar(p.type==='BOMB'?12:4);o.add(ring);}else{const trail=new THREE.Mesh(new THREE.CylinderGeometry(.06,.2,p.type==='LASER'?24:7,5).rotateX(Math.PI/2),materials[p.type]);trail.position.z=-4;o.add(trail);}group.add(o);meshes.set(p.id,o);}const a=course.at(p.s,p.lane);o.position.copy(a.p);o.position.y=p.type==='MINE'?.7:p.type==='BOMB'?1+Math.sin(Math.min(1,p.age/1.5)*Math.PI)*9:1.9;o.rotation.y=a.heading;o.visible=Math.abs(p.s-distance(player))<480;if(p.type==='MINE')o.children[0].rotation.y=time*3;}
  for(const r of racers){if(!live(r)||r.speed<20||Math.abs(distance(r)-distance(player))>220)continue;const a=course.at(r.s,lane(r));for(const side of [-1,1])if(Math.random()<dt*(r.boosting?90:28)){const x=a.p.x-Math.sin(a.heading)*4+Math.cos(a.heading)*side*.8,z=a.p.z-Math.cos(a.heading)*4-Math.sin(a.heading)*side*.8;emit(x,1.1,z,ENGINE_COLORS[r.spec??0],a.heading,r.speed*.3);}}
  for(let i=0;i<count;i++){ages[i]+=dt;if(ages[i]>1){positions[i*3+1]=-100;continue;}for(let k=0;k<3;k++)positions[i*3+k]+=velocities[i*3+k]*dt;colors[i*3]*=1-dt*2;colors[i*3+1]*=1-dt*2;colors[i*3+2]*=1-dt*2;}
  geo.attributes.position.needsUpdate=geo.attributes.color.needsUpdate=true;
  for(let i=bursts.length-1;i>=0;i--){const b=bursts[i];b.age+=dt;b.mesh.scale.setScalar(1+b.age*17);b.mesh.material.opacity=Math.max(0,1-b.age);if(b.age>1){group.remove(b.mesh);b.mesh.geometry.dispose();b.mesh.material.dispose();bursts.splice(i,1);}}
 }};
}
