import * as THREE from 'three';
import {PERKS,PERK_COLORS} from './race-rules.js';
import {ENGINE_COLORS,distance,lane,live,damageReaction} from './combat.js';
export function createCombatFX(scene){
 const group=new THREE.Group();scene.add(group);const meshes=new Map(),bursts=[],shields=new Map();
 const rocketGeo=new THREE.ConeGeometry(.35,2.5,8).rotateX(Math.PI/2),mineGeo=new THREE.IcosahedronGeometry(1.05,0),ringGeo=new THREE.TorusGeometry(1,.06,4,32);
 const materials={MISSILE:new THREE.MeshBasicMaterial({color:0xffbd79}),SEEKER:new THREE.MeshBasicMaterial({color:0xc690ff}),LASER:new THREE.MeshBasicMaterial({color:0x70efff}),MINE:new THREE.MeshBasicMaterial({color:0xff4151}),BOMB:new THREE.MeshBasicMaterial({color:0xff985a})};
 const count=600,positions=new Float32Array(count*3),colors=new Float32Array(count*3),ages=new Float32Array(count).fill(9),velocities=new Float32Array(count*3);let cursor=0;
 const geo=new THREE.BufferGeometry();geo.setAttribute('position',new THREE.BufferAttribute(positions,3));geo.setAttribute('color',new THREE.BufferAttribute(colors,3));
 const cv=document.createElement('canvas');cv.width=cv.height=32;const ctx=cv.getContext('2d'),g=ctx.createRadialGradient(16,16,0,16,16,16);g.addColorStop(0,'#fff');g.addColorStop(.25,'#bbb');g.addColorStop(1,'#000');ctx.fillStyle=g;ctx.fillRect(0,0,32,32);
 const fireCanvas=document.createElement('canvas');fireCanvas.width=fireCanvas.height=128;const fc=fireCanvas.getContext('2d'),fg=fc.createRadialGradient(64,64,0,64,64,64);fg.addColorStop(0,'rgba(255,242,203,1)');fg.addColorStop(.18,'rgba(255,174,72,.9)');fg.addColorStop(.5,'rgba(237,83,23,.35)');fg.addColorStop(1,'rgba(70,25,8,0)');fc.fillStyle=fg;fc.fillRect(0,0,128,128);const fireTexture=new THREE.CanvasTexture(fireCanvas);fireTexture.colorSpace=THREE.SRGBColorSpace;
 const particles=new THREE.Points(geo,new THREE.PointsMaterial({size:1,vertexColors:true,transparent:true,opacity:.65,alphaMap:new THREE.CanvasTexture(cv),blending:THREE.AdditiveBlending,depthWrite:false}));particles.frustumCulled=false;group.add(particles);
 function emit(x,y,z,color,heading,speed){const i=cursor++%count,c=new THREE.Color(color);positions.set([x,y,z],i*3);colors.set([c.r,c.g,c.b],i*3);velocities.set([-Math.sin(heading)*speed+(Math.random()-.5)*3,Math.random()*2,-Math.cos(heading)*speed+(Math.random()-.5)*3],i*3);ages[i]=0;}
 function burst(s,offset,course,height=2){const o=new THREE.Sprite(new THREE.SpriteMaterial({map:fireTexture,color:0xffcb8e,transparent:true,opacity:.85,depthWrite:false,blending:THREE.AdditiveBlending}));o.position.copy(course.at(s,offset).p);o.position.y=height;group.add(o);bursts.push({mesh:o,age:0});for(let j=0;j<28;j++)emit(o.position.x,height,o.position.z,0xffad56,Math.random()*Math.PI*2,7+Math.random()*20);}

 const hullGeo=new THREE.SphereGeometry(1,28,18);
 const shieldBase=new THREE.ShaderMaterial({transparent:true,depthWrite:false,side:THREE.DoubleSide,blending:THREE.AdditiveBlending,uniforms:{time:{value:0},strength:{value:1},tint:{value:new THREE.Color(0x62deff)}},vertexShader:`varying vec3 n;varying vec3 v;varying vec3 p;void main(){p=position;n=normalize(normalMatrix*normal);vec4 mv=modelViewMatrix*vec4(position,1.);v=normalize(-mv.xyz);gl_Position=projectionMatrix*mv;}`,fragmentShader:`uniform float time;uniform float strength;uniform vec3 tint;varying vec3 n;varying vec3 v;varying vec3 p;void main(){float rim=pow(1.-abs(dot(normalize(n),normalize(v))),2.5);float scan=pow(max(0.,sin(p.y*32.-time*4.)),22.);float grid=step(.96,abs(sin(atan(p.z,p.x)*12.)))*.04;float a=(rim*.24+scan*.045+grid)*strength;gl_FragColor=vec4(tint,a);}`});
 const bodyMat=new THREE.MeshStandardMaterial({color:0xa6b2b9,metalness:.8,roughness:.32}),finMat=new THREE.MeshStandardMaterial({color:0x303d45,metalness:.7,roughness:.4});
 const tubeGeo=new THREE.CylinderGeometry(.22,.28,1.8,10).rotateX(Math.PI/2),noseGeo=new THREE.ConeGeometry(.22,.7,10).rotateX(Math.PI/2),finGeo=new THREE.BoxGeometry(.08,.65,.65);
 const laserGeo=new THREE.CylinderGeometry(.09,.09,16,6).rotateX(Math.PI/2);
 const flameGeo=new THREE.ConeGeometry(.3,2,8).rotateX(-Math.PI/2);
 function rocket(type){const o=new THREE.Group();if(type==='LASER'){o.add(new THREE.Mesh(laserGeo,materials.LASER));return o;}
 const body=new THREE.Mesh(tubeGeo,bodyMat),nose=new THREE.Mesh(noseGeo,bodyMat);nose.position.z=1.2;o.add(body,nose);for(let i=0;i<4;i++){const fin=new THREE.Mesh(finGeo,finMat),a=i*Math.PI/2;fin.position.set(Math.sin(a)*.28,Math.cos(a)*.28,-.65);fin.rotation.z=-a;o.add(fin);}const flame=new THREE.Mesh(flameGeo,materials[type]);flame.position.z=-1.9;flame.name='flame';o.add(flame);return o;}
 function collect(p,course){const color=PERK_COLORS[PERKS.indexOf(p.type)]||0xffffff,a=course.at(p.s,p.offset);const mesh=new THREE.Mesh(ringGeo,new THREE.MeshBasicMaterial({color,transparent:true,depthWrite:false,blending:THREE.AdditiveBlending}));mesh.rotation.x=-Math.PI/2;mesh.position.copy(a.p);mesh.position.y=1.5;group.add(mesh);bursts.push({mesh,age:0,collect:true});for(let j=0;j<65;j++){const angle=j*Math.PI*2/65;emit(a.p.x+Math.sin(angle),2,a.p.z+Math.cos(angle),color,angle,7+Math.random()*9);}}
 function launch(r,shot,course){if(!['MISSILE','SEEKER','LASER'].includes(shot.type))return;const flash=new THREE.Sprite(new THREE.SpriteMaterial({map:fireTexture,color:shot.type==='LASER'?0x70efff:0xffd496,transparent:true,depthWrite:false,blending:THREE.AdditiveBlending}));flash.position.copy(course.at(shot.s,shot.lane).p);flash.position.y=shot.launchY;flash.scale.setScalar(2.5);group.add(flash);bursts.push({mesh:flash,age:0,life:.22,launch:true});}
 const warm=new THREE.Group();warm.visible=false;group.add(warm);
 for(const type of ['MISSILE','SEEKER','LASER'])warm.add(rocket(type));
 warm.add(new THREE.Mesh(hullGeo,shieldBase),new THREE.Mesh(ringGeo,new THREE.MeshBasicMaterial({color:0xffffff,transparent:true,depthWrite:false,blending:THREE.AdditiveBlending})),new THREE.Sprite(new THREE.SpriteMaterial({map:fireTexture,transparent:true,depthWrite:false,blending:THREE.AdditiveBlending})));
 return {group,burst,collect,launch,async prepare(renderer,camera){await renderer.compileAsync(warm,camera,scene);},clear(){for(const o of meshes.values())group.remove(o);meshes.clear();for(const b of bursts){group.remove(b.mesh);b.mesh.material.dispose();}bursts.length=0;for(const o of shields.values())o.visible=false;ages.fill(9);positions.fill(0);},update(dt,time,combat,racers,course,player,raceTime=player.raceTime||0){
  const ids=new Set(combat.shots.map(p=>p.id));for(const [id,o] of meshes)if(!ids.has(id)){group.remove(o);meshes.delete(id);}
  for(const p of combat.shots){let o=meshes.get(p.id);if(!o){if(['MINE','BOMB'].includes(p.type)){o=new THREE.Group();o.add(new THREE.Mesh(mineGeo,materials[p.type]));const ring=new THREE.Mesh(ringGeo,materials[p.type]);ring.rotation.x=-Math.PI/2;ring.scale.setScalar(p.type==='BOMB'?12:4);o.add(ring);}else o=rocket(p.type);group.add(o);meshes.set(p.id,o);}
   const a=course.at(p.s,p.lane),last=o.userData.last;o.position.copy(a.p);o.position.y=p.type==='MINE'?.7:p.type==='BOMB'?1+Math.sin(Math.min(1,p.age/1.5)*Math.PI)*9:2.5+Math.max(0,1-p.age/.65)*((p.launchY??2.5)-2.5)+Math.sin(Math.min(1,p.age/.6)*Math.PI)*.75;
   o.rotation.y=last?Math.atan2(o.position.x-last.x,o.position.z-last.z):a.heading;if(last)o.rotation.x=-Math.atan2(o.position.y-last.y,Math.hypot(o.position.x-last.x,o.position.z-last.z));o.userData.last=o.position.clone();o.visible=Math.abs(p.s-distance(player))<480;
   if(p.type==='MINE')o.children[0].rotation.y=time*3;else if(o.visible&&p.type!=='BOMB'&&p.type!=='LASER'){const flame=o.getObjectByName('flame');flame.scale.z=.8+Math.random()*.5;for(let i=0;i<3;i++)emit(o.position.x,o.position.y,o.position.z,0xffb866,o.rotation.y,16);}
  }
  for(const r of racers){let shield=shields.get(r.id);if(!shield){shield=new THREE.Mesh(hullGeo,shieldBase.clone());shield.userData.effectOnly=true;shield.raycast=()=>{};group.add(shield);shields.set(r.id,shield);}shield.visible=live(r)&&(r.shield>0||r.invulnerable>0)&&Math.abs(distance(r)-distance(player))<250;if(shield.visible){const vessel=r===player?null:r.mesh;shield.position.set(r.x,(vessel?.position.y??player.visualY??0)+1.5,r.z);shield.rotation.y=r.heading;shield.scale.set(3.6,2.6,5.7);shield.material.uniforms.time.value=time;shield.material.uniforms.strength.value=(r.shield>0?.85:.4)*(1+Math.sin(time*9)*.08);shield.material.uniforms.tint.value.setHex(r.shield>0?0x61dcff:0xffbc7d);}}
  for(const r of racers){if(!damageReaction(r,raceTime).active||Math.abs(distance(r)-distance(player))>250)continue;const y=(r===player?player.visualY:r.mesh?.position.y)??0;for(let j=0;j<2;j++)if(Math.random()<dt*55)emit(r.x+(Math.random()-.5)*2,y+1.6,r.z+(Math.random()-.5)*3,0xffa34e,Math.random()*Math.PI*2,5+Math.random()*6);}
  for(const r of racers){if(!live(r)||r.speed<20||Math.abs(distance(r)-distance(player))>220)continue;const a=course.at(r.s,lane(r));for(const side of [-1,1])if(Math.random()<dt*(r.boosting?90:28)){const x=a.p.x-Math.sin(a.heading)*4+Math.cos(a.heading)*side*.8,z=a.p.z-Math.cos(a.heading)*4-Math.sin(a.heading)*side*.8;emit(x,1.1,z,r.nitro>0?0x75ffed:ENGINE_COLORS[r.spec??0],a.heading,r.speed*.3);}}
  for(let i=0;i<count;i++){ages[i]+=dt;if(ages[i]>1){positions[i*3+1]=-100;continue;}for(let k=0;k<3;k++)positions[i*3+k]+=velocities[i*3+k]*dt;colors[i*3]*=1-dt*2;colors[i*3+1]*=1-dt*2;colors[i*3+2]*=1-dt*2;}
  geo.attributes.position.needsUpdate=geo.attributes.color.needsUpdate=true;
  for(let i=bursts.length-1;i>=0;i--){const b=bursts[i];b.age+=dt;const life=b.life||1;b.mesh.scale.setScalar(b.launch?2.5+b.age*9:1+b.age*(b.collect?13:17));if(b.collect)b.mesh.position.y+=dt*1.5;b.mesh.material.opacity=Math.max(0,1-b.age/life);if(b.age>life){group.remove(b.mesh);b.mesh.material.dispose();bursts.splice(i,1);}}
 }};
}
