import * as THREE from 'three';
import {CHAPTERS,SECTORS,BOATS,loadSave,unlocked,boatUnlocked,recordResult,objectivePassed,objectiveProgress,formatTime} from './campaign.js';
import {makeCourse,waveHeight} from './course.js';
import {loadArt,buildWorld,createBoat,animateCraft} from './world.js';
import {createWater,createWake,createSpray} from './water.js';
import {stepAI,resolvePickups,tickPerks} from './race-rules.js';
import {createAtmosphere,createLens,createReflection} from './atmosphere.js';
import {createCombat,armRacer,tickCombat,defend,pace,standings,targetFor,distance,lane,live,ENGINE_COLORS} from './combat.js';
import {createCombatFX} from './combat-fx.js';
import {createDock} from './dock.js';
import {RaceAudio} from './audio.js';
const $=id=>document.getElementById(id),clamp=THREE.MathUtils.clamp,lerp=THREE.MathUtils.lerp;
const angle=x=>Math.atan2(Math.sin(x),Math.cos(x));
let renderer,scene,camera,art,water,world,course,hero,sky,sun,env,hemi,atmosphere,lens,reflection,fill,rim;
let combatFX,dock,orbitYaw=.85,orbitPitch=.3,orbitZoom=12.5,orbitTouched=false,raceSeed=1;const combat=createCombat();
let currentSector=0,ambientAmp=.48,inspectRider=false;
let state='loading',chapter=0,boatIndex=0,mode='race',save=loadSave(),elapsed=0,clock=0,countdown=0,boostHeld=false,brakeHeld=false,stick=0,steering=0,wasBoosting=false,boostCooldown=0,air=0,airVelocity=0,pendingJump=false,lastWake=0,announcementUntil=0,toastUntil=0,previous=performance.now(),fps=60,nextHud=0;
let pausedFrom='race';const mobile=matchMedia('(pointer:coarse)').matches||innerWidth<700;
const keys=new Set(),opponents=[],race={finished:false,time:0,place:6,signals:0,pickups:0,jumps:0,boosts:0,surges:0,collisions:0};
const player={id:"player",claimed:0,shield:0,overdrive:0,x:0,z:0,heading:0,speed:0,progress:0,s:0,lateral:0,boost:100,vy:0};
const audio=new RaceAudio(),wake=createWake(mobile?480:720),spray=createSpray(mobile?800:1600);
function fatal(e){console.error(e);$('loading').hidden=true;$('error').hidden=false;$('error-text').textContent=e.message||String(e);}
window.addEventListener('error',e=>{if(state==='loading')fatal(e.error||e.message);});
function announce(text,duration=3){$('announcement').textContent=text;announcementUntil=clock+duration;}
function toast(text){$('checkpoint-toast').textContent=text;toastUntil=clock+1.5;}
function syncMenu(){
 document.querySelector('.environments').innerHTML=CHAPTERS.map((c,i)=>`<button data-course="${i}" class="${i===chapter?'active ':''}${unlocked(save,i)?'':'locked'}" aria-pressed="${i===chapter}"><b>${save.cleared[i]?'✓':String(i+1).padStart(2,'0')}</b><span>${c.short.replace('\n','<br>')}</span></button>`).join('');
 document.querySelectorAll('[data-course]').forEach(b=>b.onclick=()=>{const i=+b.dataset.course;if(!unlocked(save,i)){$('course-story').textContent=`Complete ${CHAPTERS[i-1].name} to earn this contract.`;return;}if(i!==chapter){chapter=i;changeCourse();}syncMenu();});
 const c=CHAPTERS[chapter],b=BOATS[boatIndex],available=boatUnlocked(save,boatIndex);$('course-story').textContent=c.story;$('course-objective').textContent=c.objective;$('course-distance').textContent=course?(course.length/1000).toFixed(1)+' KM · TURBO ENDURANCE':'';
 $('boatname').textContent=b.name;$('boattype').textContent=b.type;$('ridername').textContent=b.rider+' / '+b.title;$('riderbio').textContent=b.bio;$('unlock-status').textContent=available?'CREW AVAILABLE':b.unlock;$('startb').disabled=!available;$('startb').firstElementChild.textContent=available?'ENTER THE FRONTIER':'CREW LOCKED';
 ['speed','control','boost'].forEach((k,i)=>$('stat-'+k).style.width=b.stats[i]*100+'%');
 document.querySelector('.boat-options').innerHTML=BOATS.map((b,i)=>`<button data-boat="${i}" class="${i===boatIndex?'selected ':''}${boatUnlocked(save,i)?'':'locked'}" aria-label="Inspect ${b.rider} and ${b.name}${boatUnlocked(save,i)?'':' locked'}" aria-pressed="${i===boatIndex}"><span style="--paint:#${b.color.toString(16).padStart(6,'0')}"></span>${b.rider}<small>${boatUnlocked(save,i)?'READY':'LOCKED'}</small></button>`).join('');
 document.querySelectorAll('[data-boat]').forEach(b=>b.onclick=()=>{boatIndex=+b.dataset.boat;makeHero();syncMenu();});
 $('career').textContent=`${save.finishes} FINISHES / ${save.wins} WINS / ${save.reputation||0} REP · ${save.takedowns||0} TAKEDOWNS`;
}
function disposeWorld(){if(!world)return;scene.remove(world.root);world.dispose();}
function changeCourse(){
 disposeWorld();course=makeCourse(CHAPTERS[chapter]);world=buildWorld(course,art);scene.add(world.root);currentSector=0;const c=SECTORS[0];ambientAmp=c.waves;scene.fog=new THREE.FogExp2(c.sky,c.fog);scene.background=new THREE.Color(c.sky);water.uniforms.waterColor.value.set(c.water);water.uniforms.deepColor.value.set(c.deep);water.uniforms.skyColor.value.set(c.sky);water.uniforms.amplitude.value=c.waves;water.uniforms.fogDensity.value=c.fog;
 const phi=THREE.MathUtils.degToRad(90-c.sun),theta=THREE.MathUtils.degToRad(240);const dir=new THREE.Vector3().setFromSphericalCoords(1,phi,theta);if(sky.material.uniforms.sunPosition)sky.material.uniforms.sunPosition.value.copy(dir);water.uniforms.sunDirection.value.copy(dir);sun.userData.dir=dir;
 const start=course.at(180);Object.assign(player,{x:start.p.x,z:start.p.z,heading:start.heading,speed:0,progress:0,s:180,lateral:0,boost:100});if(dock){dock.position.copy(start.p);dock.rotation.y=start.heading;}if(hero)hero.position.set(player.x,0,player.z);opponents.forEach((b,i)=>{b.s=12+i*7;b.speed=0;b.mesh.visible=false;});wake.clear();camera.position.copy(start.p).add(new THREE.Vector3(18,8,-12));syncMenu();
}
function makeHero(){if(hero){scene.remove(hero);const materials=new Set();hero.traverse(o=>{if(o.isMesh)materials.add(o.material);});materials.forEach(m=>m.dispose());}hero=createBoat(art,BOATS[boatIndex].color,env,boatIndex);scene.add(hero);}
function clearInput(){document.body.classList.remove('boosting');keys.clear();boostHeld=false;brakeHeld=false;stick=0;$('stick').firstElementChild.style.transform='';}
function start(){if(!window.__READY__||!unlocked(save,chapter)||!boatUnlocked(save,boatIndex))return;audio.init().catch(()=>{});if(!audio.music)audio.loadMusic('./media/music.mp3');clearInput();world.reset();wake.clear();lens.clear();combat.reset();combatFX.clear();setupOpponents();raceSeed=crypto.getRandomValues(new Uint32Array(1))[0];Object.assign(race,{finished:false,time:0,place:mode==='race'?4:1,signals:0,pickups:0,jumps:0,boosts:0,surges:0,collisions:0});const a=course.at(0);Object.assign(player,{x:a.p.x,z:a.p.z,heading:a.heading,speed:0,progress:0,s:0,lateral:0,boost:100,shield:0,overdrive:0,claimed:0});air=0;airVelocity=0;steering=0;pendingJump=false;elapsed=0;countdown=3;boostCooldown=0;wasBoosting=false;opponents.forEach((b,i)=>{b.s=i<3?10:-3;b.speed=0;b.boost=100;b.claimed=0;b.shield=0;b.overdrive=0;b.lane=b.homeLane;b.mesh.visible=mode==='race';const a=course.at(b.s,b.lane);b.x=a.p.x;b.z=a.p.z;});armRacer(player,raceSeed);player.spec=boatIndex;opponents.forEach((b,i)=>armRacer(b,(raceSeed+i*7919)>>>0));race.eliminated=false;currentSector=-1;state='countdown';$('menu').hidden=true;$('results').hidden=true;$('pause').hidden=true;$('hud').hidden=false;$('touch').hidden=!mobile;$('sector-label').textContent=SECTORS[0].name;$('position-label').textContent=mode==='race'?'POSITION':'TIME TRIAL';$('field-size').textContent=mode==='race'?'/ 6':'/ 1';$('progress-label').textContent='SECTOR 01 / 06';announce(CHAPTERS[chapter].objective.toUpperCase(),5);audio.tone(400,.1);}
window.__START__=start;
function finish(eliminated=false){
 race.finished=!eliminated;race.eliminated=eliminated;race.time=elapsed;race.distance=player.progress;race.kills=player.kills;player.finished=!eliminated;if(!eliminated)player.finishTime=elapsed;player.speed=0;wasBoosting=false;
 race.place=mode==='time'?1:standings([player,...opponents]).indexOf(player)+1;
 const beforeRep=save.reputation||0,passed=mode==='race'&&objectivePassed(chapter,race);save=recordResult(save,chapter,race,mode);state='results';clearInput();$('touch').hidden=true;$('results').hidden=false;
 $('result-title').innerHTML=eliminated?'HULL LOST.<br>RUN ENDED.':passed?'CONTRACT<br>COMPLETE.':'FINISH LINE.<br>STILL ALIVE.';
 $('result-position').textContent=mode==='race'?race.place+' / 6':'SOLO';$('result-time').textContent=formatTime(elapsed);$('result-best').textContent='PERSONAL BEST · '+(save.best[chapter]?formatTime(save.best[chapter]):'—');
 $('result-detail').textContent=mode==='time'?'Practice time saved. Career rewards are earned in races.':`${eliminated?'Three hits. Crew evacuated.':passed?'Contract cleared.':'Finish recorded.'} +${(save.reputation||0)-beforeRep} reputation · ${player.kills} takedowns · ${race.pickups} supplies. Crew unlocks and previous records are preserved.`;
 $('result-kicker').textContent=CHAPTERS[chapter].name+' / '+(eliminated?'ELIMINATED':'FINISHED');updateStandings();audio.tone(passed?880:180,.6);
}
function updateStandings(){const rows=standings(mode==='time'?[player]:[player,...opponents]);$('standings').innerHTML=rows.map((r,i)=>`<li class="${r===player?'you':''}"><b>${i+1}</b><span>${BOATS[r.spec].rider}${r===player?' / YOU':''}<small>${BOATS[r.spec].name}</small></span><em>${r.finished?formatTime(r.finishTime):r.eliminated?'ELIMINATED · '+Math.round(distance(r)/course.length*100)+'%':Math.round(distance(r)/course.length*100)+'% · RACING'}</em><i>${'●'.repeat(Math.max(0,3-(r.hits||0)))}${'○'.repeat(r.hits||0)}</i></li>`).join('');$('standings-note').textContent=rows.some(live)?'LIVE CLASSIFICATION · Remaining crews are still racing.':'FINAL CLASSIFICATION · All crews accounted for.';}
function racers(){return mode==='race'?[player,...opponents]:[player];}
function fireWeapon(special=false){if(state!=='race')return;if(!combat.fire(player,racers(),elapsed,special))toast(player.fireCooldown>0?'LAUNCHER CYCLING':special&&!player.special?'NO SPECIAL EQUIPPED':!special&&player.ammo<=0?'MISSILES EMPTY':'NO TARGET IN RANGE');}
function shield(){if(state==='race'){if(defend(player)){toast('COUNTERMEASURE SHIELD · 5 SECONDS');audio.tone(950,.2);}else toast('NO SHIELD CHARGES');}}
function updateRivals(dt){if(mode!=='race')return;for(const b of opponents){if(!live(b))continue;tickCombat(b,dt);b.raceTime=elapsed;stepAI(b,BOATS[b.spec],course,world.pickups,dt,elapsed,chapter,racers());combat.ai(b,racers(),dt,elapsed);}}
function obstacles(dt){for(const r of racers()){if(!live(r))continue;for(const o of world.obstacles){const s=distance(r),prev=s-r.speed*dt;if(prev<o.s+5&&s>o.s-5&&Math.abs(lane(r)-o.offset)<o.radius+1.4&&elapsed-(r.lastBarrier||-10)>1){r.lastBarrier=elapsed;r.speed*=.6;r.slow=Math.max(r.slow||0,1.3);if(r===player){lens.splash(.45);toast('IMPACT · CHANGE LANES');}else r.lane+=Math.sign(r.lane-o.offset||r.homeLane||1)*5;}}}}
function updateCombat(dt){combat.update(dt,racers(),elapsed,world.obstacles);for(const event of combat.events.splice(0)){
 if(event.type==='fire'){if(event.racer===player)audio.weapon(event.weapon);}
 else if(event.type==='blast')combatFX.burst(event.s,event.lane,course);
 else{const r=event.racer;combatFX.burst(distance(r),lane(r),course);if(r===player){if(event.type==='hit'){lens.splash(.6);audio.weapon('IMPACT');toast(r.eliminated?'CRITICAL HULL FAILURE':`HULL HIT ${r.hits} / 3 · RECOVERY SHIELD`);}else toast('INCOMING BLOCKED');}else if(event.source===player){toast(event.type==='blocked'?'RIVAL SHIELD BLOCKED':r.eliminated?BOATS[r.spec].rider+' ELIMINATED':'HIT · '+BOATS[r.spec].rider+' '+r.hits+'/3');audio.tone(r.eliminated?900:650,.2);}}
 }if(state==='race'&&player.eliminated)finish(true);}
function toDock(){state='menu';lens.clear();combatFX.clear();wasBoosting=false;steering=0;clearInput();$('menu').hidden=false;$('hud').hidden=true;$('touch').hidden=true;$('results').hidden=true;$('pause').hidden=true;player.speed=0;const next=CHAPTERS.findIndex((_,i)=>!save.cleared[i]&&unlocked(save,i));if(next>=0&&save.cleared[chapter]){chapter=next;changeCourse();}else{const a=course.at(180);player.x=a.p.x;player.z=a.p.z;player.heading=a.heading;player.progress=0;player.s=180;}dock.position.set(player.x,0,player.z);dock.rotation.y=player.heading;syncMenu();}
function pause(){if(state==='race'||state==='countdown'){pausedFrom=state;audio.update(0,false,false);state='paused';clearInput();$('pause').hidden=false;$('touch').hidden=true;}else if(state==='paused'){state=pausedFrom;$('pause').hidden=true;$('touch').hidden=!mobile;previous=performance.now();}}
function recover(){if(state!=='race')return;const a=course.at(player.s);player.x=a.p.x;player.z=a.p.z;player.heading=a.heading;player.speed=8;air=airVelocity=0;toast('BACK ON COURSE');}
function control(){return clamp((keys.has('ArrowLeft')||keys.has('KeyA')?1:0)-(keys.has('ArrowRight')||keys.has('KeyD')?1:0)-stick,-1,1);}
function nextSurge(){if(!world||!course||course.sector(player.s)!==4)return null;let nearest=null;for(const g of world.surges){if(g.used)continue;const distance=((g.s-player.s)%course.length+course.length)%course.length;if(distance>course.length*.8)continue;const phase=(clock+g.phase)%10;const info={distance,open:phase<7,closesIn:phase<7?7-phase:0,opensIn:phase<7?0:10-phase};if(!nearest||distance<nearest.distance)nearest=info;}return nearest;}
function updateRace(dt){
 player.previous={x:player.x,z:player.z};tickPerks(player,dt);tickCombat(player,dt);player.raceTime=elapsed;
 const boat=BOATS[boatIndex];steering=lerp(steering,control(),1-Math.exp(-dt*7));const braking=brakeHeld||keys.has('ArrowDown')||keys.has('KeyS'),wantsBoost=player.launch>0||boostHeld||keys.has('Space');boostCooldown=Math.max(0,boostCooldown-dt);const boosting=wantsBoost&&player.boost>1&&!braking&&boostCooldown<=0;
 if(boosting&&!wasBoosting){race.boosts++;audio.tone(260,.12);}wasBoosting=boosting;
 player.boosting=boosting;if(boosting&&player.launch<=0){player.boost=Math.max(0,player.boost-dt*22);if(player.boost<=1)boostCooldown=1.2;}else player.boost=Math.min(100,player.boost+dt*(10+(player.pursuit||0)*35));
 const max=boat.speed*pace(player,racers())*(boosting?boat.boost:1)*(player.overdrive>0?1.12:1)*(braking?0:1);player.speed=lerp(player.speed,max,1-Math.exp(-dt*(braking?3.8:player.launch>0?2.8:1.35)));
 player.heading+=steering*boat.turn*(.3+.7*clamp(player.speed/30,0,1))*dt*(air>.3?.45:1);
 if(Math.abs(steering)<.08&&air<.3){const guide=course.at(player.s+20);player.heading+=angle(guide.heading-player.heading)*dt*.62;}
 player.x+=Math.sin(player.heading)*player.speed*dt;player.z+=Math.cos(player.heading)*player.speed*dt;
 const n=course.nearest(player.x,player.z,player.s);let delta=n.s-player.s;if(delta<-course.length/2)delta+=course.length;if(delta>course.length/2)delta-=course.length;if(Math.abs(delta)<100){player.progress+=delta;player.s=n.s;}player.lateral=n.lateral;
 if(n.distance>course.width-2){const push=clamp((n.distance-course.width+2)*dt*4,0,1);player.x=lerp(player.x,n.p.x,push*.35);player.z=lerp(player.z,n.p.z,push*.35);player.speed*=Math.pow(.25,dt);player.heading+=angle(n.heading-player.heading)*dt*.85;if(n.distance>course.width+8&&Math.abs(steering)<.1)player.heading=n.heading;}
 if(n.distance>course.width*2){recover();race.collisions++;}
 elapsed+=dt;
 if(air>0||airVelocity>0){airVelocity-=dt*12;air+=airVelocity*dt;if(air<=0){air=airVelocity=0;if(pendingJump){pendingJump=false;race.jumps++;lens.splash(.95);toast('CLEAN LANDING');audio.tone(590,.18);}}}
 for(const r of world.ramps){const diff=angle((player.s-r.s)/course.length*Math.PI*2)*course.length/(Math.PI*2);if(!r.used&&Math.abs(diff)<9&&Math.abs(n.lateral)<7&&player.speed>17){r.used=true;airVelocity=10.5;pendingJump=true;}}
 updateRivals(dt);obstacles(dt);
 const claims=resolvePickups(world.pickups,mode==='race'?[player,...opponents.filter(b=>!b.finished)]:[player]);
 for(const {pickup:p,racer:r} of claims){p.obj.visible=false;if(r===player){if(p.type!=='DEATH')race.pickups++;toast(p.type==='DEATH'?(player.eliminated?'LETHAL MINE':'MINE BLOCKED'):p.type+' CLAIMED');audio.tone(p.type==='DEATH'?120:730,.14);}}
 for(const g of world.surges){let d=player.s-g.s;if(d<-course.length/2)d+=course.length;if(!g.used&&Math.abs(d)<7&&g.open){g.used=true;race.surges++;player.boost=100;player.speed+=9;toast('SURGE WINDOW CAUGHT');audio.tone(920,.2);}}
 // Soft hull contacts: preserve control while preventing boats passing through each other.
 if(mode==='race'&&air<1.2)for(const [i,b] of opponents.entries()){
  if(!live(b))continue;
  const dx=player.x-b.mesh.position.x,dz=player.z-b.mesh.position.z,h=b.mesh.rotation.y;
  const longitudinal=dx*Math.sin(h)+dz*Math.cos(h),lateral=dx*Math.cos(h)-dz*Math.sin(h);
  const clearance=(BOATS[boatIndex].width+BOATS[b.spec].width)*.5;
  if(Math.abs(longitudinal)<5.5&&Math.abs(lateral)<clearance){const side=Math.sign(lateral)||(i%2?1:-1),push=(clearance-Math.abs(lateral))*Math.min(1,dt*9);player.x+=Math.cos(h)*side*push;player.z-=Math.sin(h)*side*push;if(player.shield<=0)player.speed*=Math.pow(.65,dt);if(b.shield<=0)b.speed*=Math.pow(.75,dt);if(clock-(b.contact||-10)>.7){race.collisions++;b.contact=clock;}}
 }
 race.place=mode==='time'?1:standings(racers()).indexOf(player)+1;
 document.body.classList.toggle('boosting',boosting);audio.update(player.speed,boosting,true);
 if(player.speed>30&&air<.1){const closeWake=mode==='race'&&opponents.some(b=>b.s-player.progress>3&&b.s-player.progress<20&&Math.abs(b.lane-player.lateral)<4);if(closeWake&&clock-lens.last>2.3)lens.splash(.45);else if(ambientAmp>.65&&clock-lens.last>7&&Math.sin(clock*1.7)>.96)lens.splash(.3);}
 updateCombat(dt);if(state==='race'&&player.progress>=course.length&&elapsed>10)finish();
}
function updateBoats(dt){const amp=ambientAmp;const height=waveHeight(player.x,player.z,clock,amp);hero.position.set(player.x,height-.12+air,player.z);hero.rotation.y=player.heading;const forward=waveHeight(player.x+Math.sin(player.heading)*2,player.z+Math.cos(player.heading)*2,clock,amp),back=waveHeight(player.x-Math.sin(player.heading)*2,player.z-Math.cos(player.heading)*2,clock,amp);hero.rotation.x=lerp(hero.rotation.x,-(forward-back)/4-player.speed*.0015-airVelocity*.012,1-Math.exp(-dt*5));hero.rotation.z=lerp(hero.rotation.z,-steering*.17*player.speed/38,1-Math.exp(-dt*5));
 animateCraft(hero,player.speed,wasBoosting,steering,air,dt,clock);
 opponents.forEach((b,i)=>{const a=course.at(b.s,b.lane);b.mesh.position.copy(a.p);let jump=0;if(b.speed>17&&Math.abs(b.lane)<9)for(const r of world.ramps){let d=b.s%course.length-r.s;const t=(d+9)/b.speed;if(t>0&&t<1.75)jump=Math.max(jump,10.5*t-6*t*t);}b.mesh.position.y=waveHeight(a.p.x,a.p.z,clock,amp)-.12+jump;b.mesh.rotation.set(-b.speed*.001,a.heading,Math.sin(clock+i)*.035);animateCraft(b.mesh,b.speed,b.boosting,0,jump,dt,clock+i);b.mesh.visible=mode==='race'&&state!=='menu'&&Math.abs(b.s-player.progress)<500&&b.s<course.length&&!b.eliminated;b.mesh.scale.setScalar(b.invulnerable>0&&Math.sin(clock*20)>0?.98:1);if(state==='race'&&live(b)&&b.mesh.visible&&clock-lastWake>.06&&mode==='race'){for(const side of [-1,1])wake.emit(a.p.x-Math.sin(a.heading)*3+Math.cos(a.heading)*side*1.2,.08,a.p.z-Math.cos(a.heading)*3-Math.sin(a.heading)*side*1.2,a.heading+side*.15,b.speed);};});
 if(player.speed>3&&clock-lastWake>.06&&state==='race'){lastWake=clock;const sx=Math.sin(player.heading),sz=Math.cos(player.heading);for(const side of [-1,1])wake.emit(player.x-sx*3.5+sz*side*1.1,.05,player.z-sz*3.5-sx*side*1.1,player.heading+side*.15,player.speed);if(air<.5)for(const side of [-1,1])spray.emit(player.x-sx*1.5+sz*side*1.1,.2,player.z-sz*1.5-sx*side*1.1,-sx*9+sz*side*7,-sz*9-sx*side*7,wasBoosting);}
 wake.update(dt,clock,amp);spray.update(dt);
}
const cameraTarget=new THREE.Vector3(),look=new THREE.Vector3();
function updateCamera(dt){const dir=new THREE.Vector3(Math.sin(player.heading),0,Math.cos(player.heading)),side=new THREE.Vector3(dir.z,0,-dir.x);if(state==='menu'){if(!orbitTouched)orbitYaw+=dt*.065;const yaw=player.heading+orbitYaw,radius=inspectRider?(mobile?7.5:6):orbitZoom*(mobile?1.32:1);cameraTarget.set(hero.position.x+Math.sin(yaw)*radius,hero.position.y+Math.sin(orbitPitch)*radius+1.7,hero.position.z+Math.cos(yaw)*radius);look.copy(hero.position);look.y+=inspectRider?2.1:1.3;}else{cameraTarget.copy(hero.position).addScaledVector(dir,-(mobile?12:10.5)-player.speed*.035);cameraTarget.y=hero.position.y+4.1;look.copy(hero.position).addScaledVector(dir,15);look.y=hero.position.y+1.4;}
 camera.position.lerp(cameraTarget,1-Math.exp(-dt*(state==='menu'?1.7:5)));camera.lookAt(look);camera.fov=lerp(camera.fov,(mobile?66:58)+(wasBoosting?12:0),1-Math.exp(-dt*3));camera.updateProjectionMatrix();
 fill.position.copy(hero.position).add(new THREE.Vector3(5,8,6));fill.target.position.copy(hero.position);fill.target.updateMatrixWorld();fill.intensity=state==='menu'?6:1.4;rim.position.copy(hero.position).add(new THREE.Vector3(-5,5,-8));rim.target.position.copy(hero.position);rim.target.updateMatrixWorld();
 sun.position.copy(hero.position).addScaledVector(sun.userData.dir,160);sun.target.position.copy(hero.position);sun.target.updateMatrixWorld();water.mesh.position.x=Math.round(player.x/100)*100;water.mesh.position.z=Math.round(player.z/100)*100;
}
function drawMap(){const canvas=$('minimap'),ctx=canvas.getContext('2d'),size=240;ctx.clearRect(0,0,size,size);const pts=course.samples;let max=0;for(const p of pts)max=Math.max(max,Math.abs(p.x),Math.abs(p.z));const scale=90/max;const xy=(x,z)=>[120+x*scale,120-z*scale];ctx.lineJoin='round';ctx.beginPath();pts.forEach((p,i)=>{const a=xy(p.x,p.z);i?ctx.lineTo(...a):ctx.moveTo(...a);});ctx.closePath();ctx.strokeStyle='#08283399';ctx.lineWidth=13;ctx.stroke();ctx.strokeStyle='#e9f4ee88';ctx.lineWidth=3;ctx.stroke();if(mode==='race')for(const b of opponents){const p=course.at(b.s).p;ctx.beginPath();ctx.arc(...xy(p.x,p.z),3,0,Math.PI*2);ctx.fillStyle=b.eliminated?'#514e50':'#'+ENGINE_COLORS[b.spec].toString(16).padStart(6,'0');ctx.fill();}const p=xy(player.x,player.z);ctx.save();ctx.translate(...p);ctx.rotate(player.heading);ctx.beginPath();ctx.moveTo(0,-7);ctx.lineTo(-4,5);ctx.lineTo(4,5);ctx.closePath();ctx.fillStyle='#ff7854';ctx.fill();ctx.restore();}
function updateHud(){if(state==='menu'||state==='loading')return;$('speed').textContent=String(Math.round(player.speed*3.6)).padStart(3,'0');$('timer').textContent=formatTime(elapsed);$('position').textContent=race.place;$('boostfill').style.width=player.boost+'%';$('boost-status').textContent=wasBoosting?'SURGE ACTIVE':player.shield>0?'SHIELD '+player.shield.toFixed(0)+' S':player.overdrive>0?'OVERDRIVE '+player.overdrive.toFixed(0)+' S':player.boost>25?'BOOST READY':'RECHARGING';$('progressfill').style.width=clamp(player.progress/course.length*100,0,100)+'%';$('objective-hud').innerHTML=mode==='race'?'<b>'+objectiveProgress(chapter,race)+'</b><br>'+CHAPTERS[chapter].objective:'BEAT YOUR BEST · '+(save.best[chapter]?formatTime(save.best[chapter]):'SET A TIME');const gate=nextSurge();if(gate&&gate.distance<180)$('objective-hud').innerHTML+='<br><b>'+Math.round(gate.distance)+' M · '+(gate.open?'OPEN '+gate.closesIn.toFixed(1)+' S':'OPENS IN '+gate.opensIn.toFixed(1)+' S · BRAKE TO WAIT')+'</b>';drawMap();updateCombatHud();}
function lethalAhead(){return world.pickups.find(p=>p.type==='DEATH'&&!p.collected&&p.s-player.progress>0&&p.s-player.progress<120&&Math.abs(p.offset-player.lateral)<7);}
function updateCombatHud(){
 if(state==='results'){updateStandings();return;}
 const hazard=lethalAhead(),all=racers(),target=targetFor(player,all),incoming=combat.shots.find(p=>p.owner!==player.id&&(p.target===player.id||Math.abs(p.lane-player.lateral)<5)&&player.progress-p.s>0&&player.progress-p.s<160);
 $('fireb').disabled=!target||player.ammo<=0||player.fireCooldown>0||elapsed<3;$('specialb').disabled=!player.special||player.fireCooldown>0||elapsed<3||(!['MINE','BOMB'].includes(player.special)&&!targetFor(player,all,player.special==='SEEKER'?520:340));$('shieldb').disabled=player.defenses<=0;
 $('hull').textContent='●'.repeat(Math.max(0,3-(player.hits||0)))+'○'.repeat(player.hits||0);$('hull').classList.toggle('critical',player.hits===2);
 $('ammo').textContent=player.ammo??4;$('special-label').textContent=player.special?player.special+' ×'+player.specialAmmo:'SPECIAL';$('shield-count').textContent=player.defenses??2;
 $('weapon-target').textContent=target?'LOCK · '+BOATS[target.spec].rider+' / '+Math.round(distance(target)-player.progress)+' M':'SEEK A RIVAL AHEAD · F TO FIRE';
 $('incoming').textContent=hazard?'LETHAL MINE AHEAD · CHANGE LANE / E SHIELD':incoming?'MISSILE INBOUND · CHANGE LANE / E SHIELD':player.invulnerable>0?'RECOVERY SHIELD '+Math.ceil(player.invulnerable)+' S':player.shield>0?'SHIELD ACTIVE '+Math.ceil(player.shield)+' S':player.drafting?'SLIPSTREAM +12%':player.pursuit>.01?'PURSUIT POWER +'+Math.round(player.pursuit*100)+'%':'';
 $('incoming').classList.toggle('danger',!!incoming||!!hazard);
 $('rival-list').innerHTML=standings(all).map((r,i)=>`<div class="${r===player?'self':''} ${r.eliminated?'out':''}"><b>${i+1}</b><span style="color:#${ENGINE_COLORS[r.spec??0].toString(16).padStart(6,'0')}">${r===player?'YOU':BOATS[r.spec].rider}</span><em>${r.eliminated?'OUT':r.finished?'FIN':r===player?'●'.repeat(3-(r.hits||0)):((distance(r)-player.progress)>0?'+':'')+Math.round(distance(r)-player.progress)+'m'}</em></div>`).join('');
 $('rival-tags').innerHTML=mode!=='race'?'':opponents.filter(b=>live(b)&&b.mesh.visible&&b.s-player.progress>-12&&b.s-player.progress<350).map(b=>{const v=b.mesh.position.clone();v.y+=4.6;v.project(camera);if(v.z>1||Math.abs(v.x)>1.1||Math.abs(v.y)>1.1)return '';return `<span class="rival-tag ${target===b?'locked':''}" style="left:${(v.x*.5+.5)*100}%;top:${(-v.y*.5+.5)*100}%"><b>${BOATS[b.spec].rider}</b> ${Math.round(b.s-player.progress)}m<small>${b.shield>0?'SHIELD · ':b.invulnerable>0?'RECOVERY · ':''}${'●'.repeat(3-b.hits)}${'○'.repeat(b.hits)}</small></span>`;}).join('');
 const row=world.pickups.find(p=>!p.collected&&p.s>player.progress);$('supply-distance').textContent=row?'SUPPLY LINE · '+Math.round(row.s-player.progress)+' M':'FINAL APPROACH';
}
function frame(now){requestAnimationFrame(frame);const raw=(now-previous)/1000;previous=now;const dt=Math.min(.05,raw);fps=lerp(fps,1/Math.max(raw,.001),.05);if(!hero||!world)return;if(state!=='paused'){clock+=dt;world.update(clock,player.s);updateEnvironment(dt);lens.update(dt,clock,state);water.uniforms.time.value=clock;if(state==='countdown'){const before=Math.ceil(countdown);countdown-=dt;const after=Math.ceil(countdown);$('countdown').textContent=countdown>0?after:'GO';if(after!==before)audio.tone(after>0?400:800,.1);if(countdown<=0){state='race';announce('TURBO IGNITION · WEAPONS LIVE IN 3',2.5);setTimeout(()=>$('countdown').textContent='',650);}}if(state==='race')updateRace(dt);else{audio.update(0,false,false);if(state==='results'&&opponents.some(live)&&mode==='race'){elapsed+=dt;updateRivals(dt);resolvePickups(world.pickups,opponents.filter(live));obstacles(dt);updateCombat(dt);}}updateBoats(dt);updateCamera(dt);combatFX.update(dt,clock,combat,racers(),course,player);}
 $('announcement').style.opacity=clock<announcementUntil?'1':'0';if(clock>toastUntil)$('checkpoint-toast').textContent='';world.root.visible=state!=='menu';water.mesh.visible=state!=='menu';dock.visible=state==='menu';combatFX.group.visible=state!=='menu';atmosphere.mist.visible=state!=='menu';renderer.info.reset();if(state!=='menu')reflection.update(scene,camera,water.mesh,[wake.mesh,spray.mesh,combatFX.group,...world.reflectionHidden(player.s)],clock);lens.render(scene,camera);if(now>nextHud){updateHud();nextHud=now+80;}
 const guide=course.at(player.s+clamp(player.speed*.6,12,50)).p;window.__GAME__={sector:course.sector(player.s),sectorName:course.environment(player.s).short,pickups:race.pickups,roster:BOATS.map((_,i)=>boatUnlocked(save,i)),rivals:opponents.map(b=>({id:b.id,name:BOATS[b.spec].rider,s:b.s,lane:b.lane,speed:b.speed,boost:b.boost,claimed:b.claimed,shield:b.shield,invulnerable:b.invulnerable,hits:b.hits,ammo:b.ammo,eliminated:b.eliminated,finished:b.finished,shots:b.shots,damageDealt:b.damageDealt})),nextPickup:world.pickups.filter(p=>p.type!=='DEATH'&&!p.collected&&p.s>player.progress).sort((a,b)=>(a.s-player.progress+Math.abs(a.offset-player.lateral)*3)-(b.s-player.progress+Math.abs(b.offset-player.lateral)*3)).slice(0,1).map(p=>({s:p.s,offset:p.offset,type:p.type}))[0],lethalAhead:lethalAhead()?{distance:lethalAhead().s-player.progress,offset:lethalAhead().offset}:null,weapons:{ammo:player.ammo,special:player.special,specialAmmo:player.specialAmmo,defenses:player.defenses,hits:player.hits,kills:player.kills,shots:player.shots,damageDealt:player.damageDealt,shield:player.shield,invulnerable:player.invulnerable,eliminated:player.eliminated,incoming:combat.shots.some(p=>p.owner!==player.id&&(p.target===player.id||Math.abs(p.lane-player.lateral)<5)&&player.progress-p.s>0&&player.progress-p.s<160),cooldown:player.fireCooldown,projectiles:combat.shots.length,target:targetFor(player,racers())?.id,pursuit:player.pursuit,drafting:player.drafting},obstacleAhead:world.obstacles.filter(o=>o.s>player.progress&&o.s-player.progress<160),orbit:{yaw:orbitYaw,pitch:orbitPitch},lensDrops:lens.count,surgeWindow:nextSurge(),craft:BOATS[boatIndex].name,foilAngle:hero.userData.foils[0].rotation.z,engineIntensity:hero.userData.energy[0]?.emissiveIntensity,exhaustScale:hero.userData.plumes[0]?.scale.z,air,pos:[player.x,player.z],fps,speed:player.speed,score:race.signals+race.jumps+race.surges,over:state==='results',draws:renderer.info.render.calls,tris:renderer.info.render.triangles,progress:Math.max(0,player.progress/course.length),heading:player.heading,guideHeading:Math.atan2(guide.x-player.x,guide.z-player.z),lateral:player.lateral,boost:player.boost,boosts:race.boosts,jumps:race.jumps,signals:race.signals,surges:race.surges,place:race.place,chapter,state,unlocked:CHAPTERS.map((_,i)=>unlocked(save,i)),elapsed,courseLength:course.length};
}
function bindInput(){
 window.addEventListener('keydown',e=>{if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Space'].includes(e.code))e.preventDefault();if(e.code==='Escape'&&!e.repeat)pause();if(e.code==='KeyR'&&!e.repeat)recover();if(e.code==='KeyF'&&!e.repeat)fireWeapon();if(e.code==='KeyQ'&&!e.repeat)fireWeapon(true);if(e.code==='KeyE'&&!e.repeat)shield();keys.add(e.code);});window.addEventListener('keyup',e=>keys.delete(e.code));window.addEventListener('blur',()=>{clearInput();if(state==='race'||state==='countdown')pause();});document.addEventListener('visibilitychange',()=>{if(document.hidden&&(state==='race'||state==='countdown'))pause();});
 const stickEl=$('stick');let pointer=null;const setStick=e=>{const r=stickEl.getBoundingClientRect();stick=clamp((e.clientX-r.left-r.width/2)/(r.width*.36),-1,1);stickEl.firstElementChild.style.transform=`translate(${stick*30}px, ${clamp(e.clientY-r.top-r.height/2,-25,25)}px)`;stickEl.setAttribute('aria-valuenow',stick.toFixed(2));};stickEl.onpointerdown=e=>{e.preventDefault();pointer=e.pointerId;stickEl.setPointerCapture(pointer);setStick(e);};stickEl.onpointermove=e=>{if(e.pointerId===pointer)setStick(e);};const release=()=>{pointer=null;stick=0;stickEl.firstElementChild.style.transform='';};stickEl.onpointerup=release;stickEl.onpointercancel=release;stickEl.onlostpointercapture=release;
 for(const [id,set] of [['boostb',v=>boostHeld=v],['brakeb',v=>brakeHeld=v]]){const b=$(id);b.onpointerdown=e=>{e.preventDefault();b.setPointerCapture(e.pointerId);set(true);};b.onpointerup=b.onpointercancel=b.onlostpointercapture=()=>set(false);}
 $('fireb').onclick=()=>fireWeapon();$('specialb').onclick=()=>fireWeapon(true);$('shieldb').onclick=shield;
 const zone=$('orbit-zone');let orbitPointer=null,lastX=0,lastY=0;zone.onpointerdown=e=>{orbitPointer=e.pointerId;zone.setPointerCapture(e.pointerId);lastX=e.clientX;lastY=e.clientY;orbitTouched=true;};zone.onpointermove=e=>{if(e.pointerId!==orbitPointer)return;orbitYaw-=(e.clientX-lastX)*.009;orbitPitch=clamp(orbitPitch+(e.clientY-lastY)*.005,.08,.85);lastX=e.clientX;lastY=e.clientY;zone.setAttribute('aria-valuenow',Math.round(((orbitYaw*180/Math.PI)%360+360)%360));};zone.onpointerup=zone.onpointercancel=()=>orbitPointer=null;zone.onwheel=e=>{e.preventDefault();orbitZoom=clamp(orbitZoom+e.deltaY*.012,8,21);};zone.onkeydown=e=>{if(e.code==='ArrowLeft')orbitYaw-=.2;if(e.code==='ArrowRight')orbitYaw+=.2;orbitTouched=true;};
 $('inspectb').onclick=()=>{inspectRider=!inspectRider;$('inspectb').textContent=inspectRider?'VIEW MACHINE ↗':'RIDER DETAIL ↗';};$('startb').onclick=start;$('againb').onclick=start;$('restartb').onclick=start;$('dockb').onclick=toDock;$('exitb').onclick=toDock;$('pauseb').onclick=pause;$('resumeb').onclick=pause;$('soundb').onclick=()=>{audio.setEnabled(!audio.enabled);$('soundlabel').textContent=audio.enabled?'ON':'OFF';};
 document.querySelectorAll('[data-boat]').forEach(b=>b.onclick=()=>{boatIndex=+b.dataset.boat;makeHero();syncMenu();});document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{mode=b.dataset.mode;document.querySelectorAll('[data-mode]').forEach(x=>x.classList.toggle('selected',x===b));opponents.forEach(o=>o.mesh.visible=mode==='race');});
 window.addEventListener('resize',()=>{renderer.setSize(innerWidth,innerHeight);camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();});
}

function setupOpponents(){
 for(const b of opponents){scene.remove(b.mesh);const ms=new Set();b.mesh.traverse(o=>{if(o.isMesh)ms.add(o.material);});ms.forEach(m=>m.dispose());}opponents.length=0;
 BOATS.forEach((spec,index)=>{if(index===boatIndex)return;const i=opponents.length,mesh=createBoat(art,spec.color,env,index);scene.add(mesh);opponents.push({id:'rival-'+index,index:i,spec:index,mesh,s:i<3?10:-3,speed:0,boost:100,claimed:0,lane:[-16,0,16,-12,12][i],homeLane:[-16,0,16,-12,12][i],shield:0,overdrive:0,x:0,z:0});});
}
function updateEnvironment(dt){
 const n=course.sector(player.s),c=SECTORS[n],blend=1-Math.exp(-dt*.4);
 if(n!==currentSector){currentSector=n;if(state==='race'){announce(c.short,3);audio.tone(360,.2);} $('sector-label').textContent=c.name;$('progress-label').textContent='SECTOR '+String(n+1).padStart(2,'0')+' / 06';}
 scene.fog.color.lerp(new THREE.Color(c.sky),blend);scene.fog.density=lerp(scene.fog.density,c.fog,blend);water.uniforms.skyColor.value.copy(scene.fog.color);water.uniforms.fogDensity.value=scene.fog.density;
 water.uniforms.waterColor.value.lerp(new THREE.Color(c.water),blend);water.uniforms.deepColor.value.lerp(new THREE.Color(c.deep),blend);ambientAmp=lerp(ambientAmp,c.waves,blend);water.uniforms.amplitude.value=ambientAmp;
 atmosphere.update(clock,player,state==='menu'?new THREE.Color('#17191b'):scene.fog.color,n);if(state==='menu'){scene.fog.color.set('#17191b');scene.fog.density=.007;}sun.color.lerp(new THREE.Color(n===3?0xf9a473:0xe3d8bf),blend);sun.intensity=lerp(sun.intensity,n===1?1.1:n===3?1.6:2.1,blend);hemi.intensity=lerp(hemi.intensity,n===1?1.7:2.2,blend);
}

async function init(){
 renderer=new THREE.WebGLRenderer({canvas:$('scene'),antialias:true,powerPreference:'high-performance'});renderer.setSize(innerWidth,innerHeight);renderer.setPixelRatio(Math.min(devicePixelRatio,mobile?1.5:1.7));renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=.92;renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;scene=new THREE.Scene();camera=new THREE.PerspectiveCamera(58,innerWidth/innerHeight,.3,2300);
 atmosphere=createAtmosphere();sky=atmosphere.sky;scene.add(sky,atmosphere.mist);lens=createLens(renderer,mobile);combatFX=createCombatFX(scene);dock=createDock();scene.add(dock);
 const pmrem=new THREE.PMREMGenerator(renderer);env=pmrem.fromScene(scene,.04,.1,10000).texture;scene.environment=env;scene.environmentIntensity=.12;pmrem.dispose();
 hemi=new THREE.HemisphereLight(0xc0cfda,0x626255,2.2);scene.add(hemi);sun=new THREE.DirectionalLight(0xf0d6b4,2.1);sun.castShadow=true;sun.shadow.mapSize.set(mobile?1024:2048,mobile?1024:2048);sun.shadow.camera.left=-75;sun.shadow.camera.right=75;sun.shadow.camera.top=75;sun.shadow.camera.bottom=-75;sun.shadow.camera.near=1;sun.shadow.camera.far=350;sun.shadow.bias=-.0004;sun.shadow.normalBias=.04;scene.add(sun,sun.target);
 fill=new THREE.DirectionalLight(0xc1d7de,2.1);rim=new THREE.DirectionalLight(0xf3c18a,1.1);scene.add(fill,fill.target,rim,rim.target);
 art=await loadArt(p=>{$('loadfill').style.width=(10+p*75)+'%';$('loadtext').textContent=p<.55?'Preparing your machine…':'Charting the Atlantic…';});
 water=createWater(art.textures['water-normal']);scene.add(water.mesh,wake.mesh,spray.mesh);reflection=createReflection(renderer,water,mobile);renderer.info.autoReset=false;makeHero();setupOpponents();changeCourse();bindInput();state='menu';$('loadfill').style.width='100%';renderer.compile(scene,camera);requestAnimationFrame(frame);$('loading').hidden=true;$('menu').hidden=false;syncMenu();window.__READY__=true;
}
init().catch(fatal);
