import * as THREE from 'three';
import {Sky} from 'three/addons/objects/Sky.js';
import {CHAPTERS,BOATS,loadSave,unlocked,recordResult,objectivePassed,objectiveProgress,formatTime} from './campaign.js';
import {makeCourse,waveHeight} from './course.js';
import {loadArt,buildWorld,createBoat} from './world.js';
import {createWater,createWake,createSpray} from './water.js';
import {RaceAudio} from './audio.js';
const $=id=>document.getElementById(id),clamp=THREE.MathUtils.clamp,lerp=THREE.MathUtils.lerp;
const angle=x=>Math.atan2(Math.sin(x),Math.cos(x));
let renderer,scene,camera,art,water,world,course,hero,sky,sun,env;
let state='loading',chapter=0,boatIndex=0,mode='race',save=loadSave(),elapsed=0,clock=0,countdown=0,boostHeld=false,brakeHeld=false,stick=0,steering=0,wasBoosting=false,boostCooldown=0,air=0,airVelocity=0,pendingJump=false,lastWake=0,announcementUntil=0,toastUntil=0,previous=performance.now(),fps=60,nextHud=0;
let pausedFrom='race';const mobile=matchMedia('(pointer:coarse)').matches||innerWidth<700;
const keys=new Set(),opponents=[],race={finished:false,time:0,place:6,signals:0,jumps:0,boosts:0,surges:0,collisions:0};
const player={x:0,z:0,heading:0,speed:0,progress:0,s:0,lateral:0,boost:100,vy:0};
const audio=new RaceAudio(),wake=createWake(mobile?240:380),spray=createSpray(mobile?240:500);
function fatal(e){console.error(e);$('loading').hidden=true;$('error').hidden=false;$('error-text').textContent=e.message||String(e);}
window.addEventListener('error',e=>{if(state==='loading')fatal(e.error||e.message);});
function announce(text,duration=3){$('announcement').textContent=text;announcementUntil=clock+duration;}
function toast(text){$('checkpoint-toast').textContent=text;toastUntil=clock+1.5;}
function syncMenu(){
 document.querySelector('.environments').innerHTML=CHAPTERS.map((c,i)=>`<button data-course="${i}" class="${i===chapter?'active ':''}${unlocked(save,i)?'':'locked'}" aria-label="${c.name}${unlocked(save,i)?'':' locked'}" aria-pressed="${i===chapter}"><b>${save.cleared[i]?'✓':String(i+1).padStart(2,'0')}</b><span>${c.short.replace('\n','<br>')}</span></button>`).join('');
 document.querySelectorAll('[data-course]').forEach(b=>b.onclick=()=>{const i=+b.dataset.course;if(!unlocked(save,i)){$('course-story').textContent=`Complete ${CHAPTERS[i-1].name}: ${CHAPTERS[i-1].objective.toLowerCase()}.`;$('course-objective').textContent='CLEARANCE REQUIRED';return;}if(i!==chapter){chapter=i;changeCourse();}syncMenu();});
 const c=CHAPTERS[chapter];$('course-story').textContent=c.story;$('course-objective').textContent=save.cleared[chapter]?'CLEARED · '+(save.best[chapter]?formatTime(save.best[chapter]):''):c.objective;$('course-distance').textContent=course?(course.length/1000).toFixed(2)+' KM':'';
 $('boatname').textContent=BOATS[boatIndex].name;$('boattype').textContent=BOATS[boatIndex].type;['speed','control','boost'].forEach((k,i)=>$('stat-'+k).style.width=BOATS[boatIndex].stats[i]*100+'%');
 document.querySelectorAll('[data-boat]').forEach(b=>{b.classList.toggle('selected',+b.dataset.boat===boatIndex);b.setAttribute('aria-pressed',String(+b.dataset.boat===boatIndex));});
}
function disposeWorld(){if(!world)return;scene.remove(world.root);world.dispose();}
function changeCourse(){
 disposeWorld();course=makeCourse(CHAPTERS[chapter]);world=buildWorld(course,art);scene.add(world.root);const c=CHAPTERS[chapter];scene.fog=new THREE.FogExp2(c.sky,c.fog);scene.background=new THREE.Color(c.sky);water.uniforms.waterColor.value.set(c.water);water.uniforms.deepColor.value.set(c.deep);water.uniforms.skyColor.value.set(c.sky);water.uniforms.amplitude.value=c.waves;water.uniforms.fogDensity.value=c.fog;
 const phi=THREE.MathUtils.degToRad(90-c.sun),theta=THREE.MathUtils.degToRad(240);const dir=new THREE.Vector3().setFromSphericalCoords(1,phi,theta);sky.material.uniforms.sunPosition.value.copy(dir);water.uniforms.sunDirection.value.copy(dir);sun.userData.dir=dir;
 const start=course.at(0);Object.assign(player,{x:start.p.x,z:start.p.z,heading:start.heading,speed:0,progress:0,s:0,lateral:0,boost:100});if(hero)hero.position.set(player.x,0,player.z);opponents.forEach((b,i)=>{b.s=12+i*7;b.speed=0;b.mesh.visible=mode==='race';});wake.clear();camera.position.copy(start.p).add(new THREE.Vector3(18,8,-12));syncMenu();
}
function makeHero(){if(hero)scene.remove(hero);hero=createBoat(art,BOATS[boatIndex].color,env);scene.add(hero);}
function clearInput(){keys.clear();boostHeld=false;brakeHeld=false;stick=0;$('stick').firstElementChild.style.transform='';}
function start(){if(!window.__READY__||!unlocked(save,chapter))return;audio.init().catch(()=>{});if(!audio.music)audio.loadMusic('./media/music.mp3');clearInput();world.reset();wake.clear();Object.assign(race,{finished:false,time:0,place:mode==='race'?6:1,signals:0,jumps:0,boosts:0,surges:0,collisions:0});const a=course.at(0);Object.assign(player,{x:a.p.x,z:a.p.z,heading:a.heading,speed:0,progress:0,s:0,lateral:0,boost:100});air=0;airVelocity=0;pendingJump=false;elapsed=0;countdown=3;boostCooldown=0;wasBoosting=false;opponents.forEach((b,i)=>{b.s=10+i*6;b.speed=0;b.mesh.visible=mode==='race';});state='countdown';$('menu').hidden=true;$('results').hidden=true;$('pause').hidden=true;$('hud').hidden=false;$('touch').hidden=!mobile;$('sector-label').textContent=CHAPTERS[chapter].name;$('position-label').textContent=mode==='race'?'POSITION':'TIME TRIAL';$('field-size').textContent=mode==='race'?'/ 6':'/ 1';$('progress-label').textContent='CHAPTER '+String(chapter+1).padStart(2,'0')+' / 06';announce(CHAPTERS[chapter].objective.toUpperCase(),5);audio.tone(400,.1);}
window.__START__=start;
function finish(){race.finished=true;race.time=elapsed;race.place=mode==='time'?1:1+opponents.filter(b=>b.s>player.progress).length;const passed=mode==='race'&&objectivePassed(chapter,race),first=passed&&!save.cleared[chapter];save=recordResult(save,chapter,race,mode);state='results';clearInput();$('touch').hidden=true;$('results').hidden=false;$('result-title').innerHTML=passed?(chapter===5?'ATLANTIC<br>CHAMPION.':'PASSAGE<br>EARNED.'):'RUN<br>COMPLETE.';$('result-position').textContent=mode==='race'?race.place+' / 6':'SOLO';$('result-time').textContent=formatTime(elapsed);$('result-best').textContent='PERSONAL BEST · '+formatTime(save.best[chapter]);$('result-detail').textContent=first&&chapter<5?CHAPTERS[chapter+1].name+' is now unlocked.':passed?'Clearance secured. Return to the dock to choose your next race.':mode==='time'?'Time trials improve your record. Complete the race challenge to earn your next clearance.':'Still to earn: '+CHAPTERS[chapter].objective+'. '+objectiveProgress(chapter,race);$('result-kicker').textContent=CHAPTERS[chapter].name+' / COMPLETE';audio.tone(passed?880:440,.6);}
function toDock(){state='menu';wasBoosting=false;clearInput();$('menu').hidden=false;$('hud').hidden=true;$('touch').hidden=true;$('results').hidden=true;$('pause').hidden=true;player.speed=0;const next=CHAPTERS.findIndex((_,i)=>!save.cleared[i]&&unlocked(save,i));if(next>=0&&save.cleared[chapter]){chapter=next;changeCourse();}else{const a=course.at(0);player.x=a.p.x;player.z=a.p.z;player.heading=a.heading;player.progress=player.s=0;}syncMenu();}
function pause(){if(state==='race'||state==='countdown'){pausedFrom=state;audio.update(0,false,false);state='paused';clearInput();$('pause').hidden=false;$('touch').hidden=true;}else if(state==='paused'){state=pausedFrom;$('pause').hidden=true;$('touch').hidden=!mobile;previous=performance.now();}}
function recover(){if(state!=='race')return;const a=course.at(player.s);player.x=a.p.x;player.z=a.p.z;player.heading=a.heading;player.speed=8;air=airVelocity=0;toast('BACK ON COURSE');}
function control(){return clamp((keys.has('ArrowLeft')||keys.has('KeyA')?1:0)-(keys.has('ArrowRight')||keys.has('KeyD')?1:0)-stick,-1,1);}
function updateRace(dt){
 const boat=BOATS[boatIndex];steering=lerp(steering,control(),1-Math.exp(-dt*7));const braking=brakeHeld||keys.has('ArrowDown')||keys.has('KeyS'),wantsBoost=boostHeld||keys.has('Space');boostCooldown=Math.max(0,boostCooldown-dt);const boosting=wantsBoost&&player.boost>1&&!braking&&boostCooldown<=0;
 if(boosting&&!wasBoosting){race.boosts++;audio.tone(260,.12);}wasBoosting=boosting;
 if(boosting){player.boost=Math.max(0,player.boost-dt*22);if(player.boost<=1)boostCooldown=1.2;}else player.boost=Math.min(100,player.boost+dt*5.5);
 const max=boat.speed*(boosting?boat.boost:1)*(braking?.3:1);player.speed=lerp(player.speed,max,1-Math.exp(-dt*(braking?2.8:.85)));
 player.heading+=steering*boat.turn*(.3+.7*clamp(player.speed/30,0,1))*dt*(air>.3?.45:1);
 if(Math.abs(steering)<.08&&air<.3){const guide=course.at(player.s+20);player.heading+=angle(guide.heading-player.heading)*dt*.26;}
 player.x+=Math.sin(player.heading)*player.speed*dt;player.z+=Math.cos(player.heading)*player.speed*dt;
 const n=course.nearest(player.x,player.z,player.s);let delta=n.s-player.s;if(delta<-course.length/2)delta+=course.length;if(delta>course.length/2)delta-=course.length;if(Math.abs(delta)<100){player.progress+=delta;player.s=n.s;}player.lateral=n.lateral;
 if(n.distance>course.width-2){const push=clamp((n.distance-course.width+2)*dt*4,0,1);player.x=lerp(player.x,n.p.x,push*.35);player.z=lerp(player.z,n.p.z,push*.35);player.speed*=Math.pow(.25,dt);player.heading+=angle(n.heading-player.heading)*dt*.85;if(n.distance>course.width+8&&Math.abs(steering)<.1)player.heading=n.heading;}
 if(n.distance>course.width*2){recover();race.collisions++;}
 elapsed+=dt;
 if(air>0||airVelocity>0){airVelocity-=dt*12;air+=airVelocity*dt;if(air<=0){air=airVelocity=0;if(pendingJump){pendingJump=false;race.jumps++;toast('CLEAN LANDING');audio.tone(590,.18);}}}
 for(const r of world.ramps){const diff=angle((player.s-r.s)/course.length*Math.PI*2)*course.length/(Math.PI*2);if(!r.used&&Math.abs(diff)<9&&Math.abs(n.lateral)<7&&player.speed>17){r.used=true;airVelocity=10.5;pendingJump=true;}}
 for(const p of world.pickups){if(p.collected)continue;const dx=p.obj.position.x-player.x,dz=p.obj.position.z-player.z;if(dx*dx+dz*dz<45){p.collected=true;p.obj.visible=false;player.boost=Math.min(100,player.boost+27);if(p.signal)race.signals++;toast(p.signal?'SIGNAL RECOVERED · '+Math.min(race.signals,4)+'/4':'BOOST +27');audio.tone(p.signal?820:680,.14);}}
 for(const g of world.surges){let d=player.s-g.s;if(d<-course.length/2)d+=course.length;if(!g.used&&Math.abs(d)<7&&g.open){g.used=true;race.surges++;player.boost=100;player.speed+=9;toast('SURGE WINDOW CAUGHT');audio.tone(920,.2);}}
 // Soft hull contacts: preserve control while preventing boats passing through each other.
 if(mode==='race'&&air<1.2)for(const [i,b] of opponents.entries()){
  const dx=player.x-b.mesh.position.x,dz=player.z-b.mesh.position.z,h=b.mesh.rotation.y;
  const longitudinal=dx*Math.sin(h)+dz*Math.cos(h),lateral=dx*Math.cos(h)-dz*Math.sin(h);
  if(Math.abs(longitudinal)<5.5&&Math.abs(lateral)<3.5){const side=Math.sign(lateral)||(i%2?1:-1),push=(3.5-Math.abs(lateral))*Math.min(1,dt*9);player.x+=Math.cos(h)*side*push;player.z-=Math.sin(h)*side*push;player.speed*=Math.pow(.75,dt);if(clock-(b.contact||-10)>.7){race.collisions++;b.contact=clock;}}
 }
 opponents.forEach((b,i)=>{const target=30.5+i*.65+chapter*.2+Math.sin(elapsed*.34+i)*2.5;const rubber=clamp((player.progress-b.s)*.007,-1.5,2);b.speed=lerp(b.speed,target+rubber,1-Math.exp(-dt));b.s+=b.speed*dt;});
 race.place=mode==='time'?1:1+opponents.filter(b=>b.s>player.progress).length;
 document.body.classList.toggle('boosting',boosting);audio.update(player.speed,boosting,true);
 if(player.progress>=course.length&&elapsed>10)finish();
}
function updateBoats(dt){const amp=CHAPTERS[chapter].waves;const height=waveHeight(player.x,player.z,clock,amp);hero.position.set(player.x,height-.12+air,player.z);hero.rotation.y=player.heading;const forward=waveHeight(player.x+Math.sin(player.heading)*2,player.z+Math.cos(player.heading)*2,clock,amp),back=waveHeight(player.x-Math.sin(player.heading)*2,player.z-Math.cos(player.heading)*2,clock,amp);hero.rotation.x=lerp(hero.rotation.x,-(forward-back)/4-player.speed*.0015-airVelocity*.012,1-Math.exp(-dt*5));hero.rotation.z=lerp(hero.rotation.z,-steering*.17*player.speed/38,1-Math.exp(-dt*5));
 opponents.forEach((b,i)=>{const a=course.at(b.s,(i-2)*4+Math.sin(clock*.6+i)*1.5);b.mesh.position.copy(a.p);let jump=0;if(b.speed>17&&Math.abs((i-2)*4+Math.sin(clock*.6+i)*1.5)<9)for(const r of world.ramps){let d=b.s%course.length-r.s;const t=(d+9)/b.speed;if(t>0&&t<1.75)jump=Math.max(jump,10.5*t-6*t*t);}b.mesh.position.y=waveHeight(a.p.x,a.p.z,clock,amp)-.12+jump;b.mesh.rotation.set(-b.speed*.001,a.heading,Math.sin(clock+i)*.035);if(state==='race'&&clock-lastWake>.06&&mode==='race')wake.emit(a.p.x-Math.sin(a.heading)*3,.08,a.p.z-Math.cos(a.heading)*3,a.heading,b.speed);});
 if(player.speed>3&&clock-lastWake>.06&&state==='race'){lastWake=clock;const sx=Math.sin(player.heading),sz=Math.cos(player.heading);wake.emit(player.x-sx*3.5,.05,player.z-sz*3.5,player.heading,player.speed);if(air<.5)spray.emit(player.x-sx*2.7,.35,player.z-sz*2.7,-sx*4,-sz*4,wasBoosting);}
 wake.update(dt,clock,amp);spray.update(dt);
}
const cameraTarget=new THREE.Vector3(),look=new THREE.Vector3();
function updateCamera(dt){const dir=new THREE.Vector3(Math.sin(player.heading),0,Math.cos(player.heading)),side=new THREE.Vector3(dir.z,0,-dir.x);if(state==='menu'){const orbit=.15*Math.sin(clock*.12);cameraTarget.copy(hero.position).addScaledVector(dir,10+orbit*4).addScaledVector(side,13);cameraTarget.y=6.8;look.copy(hero.position).addScaledVector(side,-2).addScaledVector(dir,-1);look.y=1.1;}else{cameraTarget.copy(hero.position).addScaledVector(dir,-(mobile?14.5:12.5)-player.speed*.035);cameraTarget.y=hero.position.y+5.5;look.copy(hero.position).addScaledVector(dir,15);look.y=hero.position.y+1.4;}
 camera.position.lerp(cameraTarget,1-Math.exp(-dt*(state==='menu'?1.7:5)));camera.lookAt(look);camera.fov=lerp(camera.fov,(mobile?66:58)+(wasBoosting?8:0),1-Math.exp(-dt*3));camera.updateProjectionMatrix();
 sun.position.copy(hero.position).addScaledVector(sun.userData.dir,160);sun.target.position.copy(hero.position);sun.target.updateMatrixWorld();water.mesh.position.x=Math.round(player.x/100)*100;water.mesh.position.z=Math.round(player.z/100)*100;
}
function drawMap(){const canvas=$('minimap'),ctx=canvas.getContext('2d'),size=240;ctx.clearRect(0,0,size,size);const pts=course.samples;let max=0;for(const p of pts)max=Math.max(max,Math.abs(p.x),Math.abs(p.z));const scale=90/max;const xy=(x,z)=>[120+x*scale,120-z*scale];ctx.lineJoin='round';ctx.beginPath();pts.forEach((p,i)=>{const a=xy(p.x,p.z);i?ctx.lineTo(...a):ctx.moveTo(...a);});ctx.closePath();ctx.strokeStyle='#08283399';ctx.lineWidth=13;ctx.stroke();ctx.strokeStyle='#e9f4ee88';ctx.lineWidth=3;ctx.stroke();if(mode==='race')for(const b of opponents){const p=course.at(b.s).p;ctx.beginPath();ctx.arc(...xy(p.x,p.z),3,0,Math.PI*2);ctx.fillStyle='#adc2c7';ctx.fill();}const p=xy(player.x,player.z);ctx.save();ctx.translate(...p);ctx.rotate(player.heading);ctx.beginPath();ctx.moveTo(0,-7);ctx.lineTo(-4,5);ctx.lineTo(4,5);ctx.closePath();ctx.fillStyle='#ff7854';ctx.fill();ctx.restore();}
function updateHud(){if(state==='menu'||state==='loading')return;$('speed').textContent=String(Math.round(player.speed*3.6)).padStart(3,'0');$('timer').textContent=formatTime(elapsed);$('position').textContent=race.place;$('boostfill').style.width=player.boost+'%';$('boost-status').textContent=wasBoosting?'SURGE ACTIVE':player.boost>25?'SURGE READY':'RECHARGING';$('progressfill').style.width=clamp(player.progress/course.length*100,0,100)+'%';$('objective-hud').innerHTML=mode==='race'?'<b>'+objectiveProgress(chapter,race)+'</b><br>'+CHAPTERS[chapter].objective:'BEAT YOUR BEST · '+(save.best[chapter]?formatTime(save.best[chapter]):'SET A TIME');drawMap();}
function frame(now){requestAnimationFrame(frame);const raw=(now-previous)/1000;previous=now;const dt=Math.min(.05,raw);fps=lerp(fps,1/Math.max(raw,.001),.05);if(!hero||!world)return;if(state!=='paused'){clock+=dt;world.update(clock);water.uniforms.time.value=clock;if(state==='countdown'){const before=Math.ceil(countdown);countdown-=dt;const after=Math.ceil(countdown);$('countdown').textContent=countdown>0?after:'GO';if(after!==before)audio.tone(after>0?400:800,.1);if(countdown<=0){state='race';announce('FIND YOUR LINE',1.8);setTimeout(()=>$('countdown').textContent='',650);}}if(state==='race')updateRace(dt);else audio.update(0,false,false);updateBoats(dt);updateCamera(dt);}
 $('announcement').style.opacity=clock<announcementUntil?'1':'0';if(clock>toastUntil)$('checkpoint-toast').textContent='';renderer.render(scene,camera);if(now>nextHud){updateHud();nextHud=now+80;}
 const guide=course.at(player.s+clamp(player.speed*.6,12,30)).p;window.__GAME__={pos:[player.x,player.z],fps,speed:player.speed,score:race.signals+race.jumps+race.surges,over:state==='results',draws:renderer.info.render.calls,tris:renderer.info.render.triangles,progress:Math.max(0,player.progress/course.length),heading:player.heading,guideHeading:Math.atan2(guide.x-player.x,guide.z-player.z),lateral:player.lateral,boost:player.boost,boosts:race.boosts,jumps:race.jumps,signals:race.signals,surges:race.surges,place:race.place,chapter,state,unlocked:CHAPTERS.map((_,i)=>unlocked(save,i)),elapsed,courseLength:course.length};
}
function bindInput(){
 window.addEventListener('keydown',e=>{if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Space'].includes(e.code))e.preventDefault();if(e.code==='Escape'&&!e.repeat)pause();if(e.code==='KeyR'&&!e.repeat)recover();keys.add(e.code);});window.addEventListener('keyup',e=>keys.delete(e.code));window.addEventListener('blur',()=>{clearInput();if(state==='race'||state==='countdown')pause();});document.addEventListener('visibilitychange',()=>{if(document.hidden&&(state==='race'||state==='countdown'))pause();});
 const stickEl=$('stick');let pointer=null;const setStick=e=>{const r=stickEl.getBoundingClientRect();stick=clamp((e.clientX-r.left-r.width/2)/(r.width*.36),-1,1);stickEl.firstElementChild.style.transform=`translate(${stick*30}px, ${clamp(e.clientY-r.top-r.height/2,-25,25)}px)`;stickEl.setAttribute('aria-valuenow',stick.toFixed(2));};stickEl.onpointerdown=e=>{e.preventDefault();pointer=e.pointerId;stickEl.setPointerCapture(pointer);setStick(e);};stickEl.onpointermove=e=>{if(e.pointerId===pointer)setStick(e);};const release=()=>{pointer=null;stick=0;stickEl.firstElementChild.style.transform='';};stickEl.onpointerup=release;stickEl.onpointercancel=release;stickEl.onlostpointercapture=release;
 for(const [id,set] of [['boostb',v=>boostHeld=v],['brakeb',v=>brakeHeld=v]]){const b=$(id);b.onpointerdown=e=>{e.preventDefault();b.setPointerCapture(e.pointerId);set(true);};b.onpointerup=b.onpointercancel=b.onlostpointercapture=()=>set(false);}
 $('startb').onclick=start;$('againb').onclick=start;$('restartb').onclick=start;$('dockb').onclick=toDock;$('exitb').onclick=toDock;$('pauseb').onclick=pause;$('resumeb').onclick=pause;$('soundb').onclick=()=>{audio.setEnabled(!audio.enabled);$('soundlabel').textContent=audio.enabled?'ON':'OFF';};
 document.querySelectorAll('[data-boat]').forEach(b=>b.onclick=()=>{boatIndex=+b.dataset.boat;makeHero();syncMenu();});document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{mode=b.dataset.mode;document.querySelectorAll('[data-mode]').forEach(x=>x.classList.toggle('selected',x===b));opponents.forEach(o=>o.mesh.visible=mode==='race');});
 window.addEventListener('resize',()=>{renderer.setSize(innerWidth,innerHeight);camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();});
}
async function init(){
 renderer=new THREE.WebGLRenderer({canvas:$('scene'),antialias:true,powerPreference:'high-performance'});renderer.setSize(innerWidth,innerHeight);renderer.setPixelRatio(Math.min(devicePixelRatio,mobile?1.5:1.7));renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=.92;renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;scene=new THREE.Scene();camera=new THREE.PerspectiveCamera(58,innerWidth/innerHeight,.3,2300);
 sky=new Sky();sky.scale.setScalar(6000);sky.material.uniforms.turbidity.value=2.2;sky.material.uniforms.rayleigh.value=2.3;sky.material.uniforms.mieCoefficient.value=.003;sky.material.uniforms.mieDirectionalG.value=.82;sky.material.uniforms.sunPosition.value.set(-.7,.4,-.5);scene.add(sky);
 const pmrem=new THREE.PMREMGenerator(renderer);env=pmrem.fromScene(scene,.04,.1,10000).texture;scene.environment=env;scene.environmentIntensity=.12;pmrem.dispose();
 scene.add(new THREE.HemisphereLight(0xa5dbf3,0x233b38,.9));sun=new THREE.DirectionalLight(0xffe0b0,2.6);sun.castShadow=true;sun.shadow.mapSize.set(mobile?1024:2048,mobile?1024:2048);sun.shadow.camera.left=-75;sun.shadow.camera.right=75;sun.shadow.camera.top=75;sun.shadow.camera.bottom=-75;sun.shadow.camera.near=1;sun.shadow.camera.far=350;sun.shadow.bias=-.0004;sun.shadow.normalBias=.04;scene.add(sun,sun.target);
 art=await loadArt(p=>{$('loadfill').style.width=(10+p*75)+'%';$('loadtext').textContent=p<.55?'Preparing your machine…':'Charting the Atlantic…';});
 water=createWater(art.textures['water-normal']);scene.add(water.mesh,wake.mesh,spray.mesh);makeHero();for(let i=0;i<5;i++){const mesh=createBoat(art,[0xe4cf70,0x54a8ca,0xf0efdf,0x955ec4,0x46987b][i],env);scene.add(mesh);opponents.push({mesh,s:10+i*6,speed:0});}changeCourse();bindInput();state='menu';$('loadfill').style.width='100%';renderer.compile(scene,camera);requestAnimationFrame(frame);$('loading').hidden=true;$('menu').hidden=false;$('startb').disabled=false;window.__READY__=true;
}
init().catch(fatal);
