import * as THREE from 'three';
import {ASSET,bakeStatic} from './assetlib.js';
import {rng} from './course.js';
const names=['boat','rock','mangrove','crane','gate','buoy','ramp','lighthouse','quay'];
export async function loadArt(onProgress){const prototypes={};let done=0;await Promise.all(names.map(async name=>{const o=await ASSET(`./assets/${name}.js`);let meshes=0;o.traverse(n=>{if(n.isMesh)meshes++;});if(!meshes)throw Error(`The ${name} asset did not load.`);prototypes[name]=o;onProgress(++done/16);}));const loader=new THREE.TextureLoader();const textures={};await Promise.all(['water-normal','basalt','basalt-normal','bark','bark-normal','concrete','concrete-normal'].map(async name=>{const tex=await loader.loadAsync(`./media/${name}.webp`);tex.wrapS=tex.wrapT=THREE.RepeatWrapping;tex.anisotropy=4;if(!name.endsWith('normal'))tex.colorSpace=THREE.SRGBColorSpace;textures[name]=tex;onProgress(++done/16);}));return{prototypes,textures};}
function surface(material,map,normal,scale){const m=material.clone();m.map=map;m.normalMap=normal;m.normalScale.set(.48,.48);m.onBeforeCompile=shader=>{shader.vertexShader=shader.vertexShader.replace('#include <common>','#include <common>\nvarying vec3 surfaceP;varying vec3 surfaceN;').replace('#include <begin_vertex>','#include <begin_vertex>\nsurfaceP=(modelMatrix*vec4(position,1.)).xyz;surfaceN=normalize(mat3(modelMatrix)*normal);');shader.fragmentShader=shader.fragmentShader.replace('#include <common>','#include <common>\nvarying vec3 surfaceP;varying vec3 surfaceN;').replace('#include <map_fragment>',`vec3 sw=pow(abs(surfaceN),vec3(4.));sw/=max(dot(sw,vec3(1.)),.001);vec3 sp=surfaceP*${scale.toFixed(4)};vec4 texelColor=texture2D(map,sp.yz)*sw.x+texture2D(map,sp.xz)*sw.y+texture2D(map,sp.xy)*sw.z;float macro=texture2D(map,sp.xz*.11).r;diffuseColor*=vec4(texelColor.rgb*(.88+macro*.3),1.);`);};m.customProgramCacheKey=()=>`triplanar-${scale}`;return m;}
export function createBoat(art,color,env){const boat=art.prototypes.boat.clone(true);const materials=new Map();boat.traverse(o=>{if(!o.isMesh)return;const old=o.material;if(!materials.has(old.uuid)){let m;if(old.name==='paint'||old.name==='ivory'){m=new THREE.MeshPhysicalMaterial({color:old.name==='paint'?color:0xebe7d8,metalness:.28,roughness:.3,clearcoat:1,clearcoatRoughness:.2,envMap:env,envMapIntensity:.13});}else{m=old.clone();m.envMap=env;m.envMapIntensity=old.name==='glass'?.18:.10;}materials.set(old.uuid,m);}o.material=materials.get(old.uuid);o.castShadow=true;});return boat;}
function textPlane(text,width=12,height=2,color='#e4ede8',bg='#17333d'){const c=document.createElement('canvas');c.width=1024;c.height=128;const x=c.getContext('2d');x.fillStyle=bg;x.fillRect(0,0,1024,128);x.fillStyle=color;x.font='bold 64px Arial';x.textAlign='center';x.textBaseline='middle';x.fillText(text,512,69);const t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;const mesh=new THREE.Mesh(new THREE.PlaneGeometry(width,height),new THREE.MeshBasicMaterial({map:t,side:THREE.FrontSide}));return mesh;}
export function buildWorld(course,art){
 const {config:c}=course,random=rng(c.seed),root=new THREE.Group(),chunks=Array.from({length:12},()=>new THREE.Group()),dynamic=new THREE.Group();root.add(dynamic);const materialCache=new Map();
 function clone(name){const o=art.prototypes[name].clone(true);o.traverse(m=>{if(!m.isMesh)return;const old=m.material,key=old.uuid+'-'+name;if(!materialCache.has(key)){let mat=old;if(old.name==='stone'){mat=surface(old,art.textures[name==='rock'?'basalt':'concrete'],art.textures[name==='rock'?'basalt-normal':'concrete-normal'],.09);mat.color.set(name==='rock'?(c.kind==='volcano'?0xb2a6a0:0xf3e4cf):0xf1e3c5);if(name==='rock'&&c.kind==='volcano'){const compile=mat.onBeforeCompile;mat.onBeforeCompile=shader=>{compile(shader);shader.fragmentShader=shader.fragmentShader.replace('#include <emissivemap_fragment>',`#include <emissivemap_fragment>
 float fissure=abs(sin(surfaceP.x*.21+sin(surfaceP.y*.23)*.32)*sin(surfaceP.z*.25+cos(surfaceP.y*.31)*.3));float ember=(1.-smoothstep(.018,.045,fissure))*(1.-smoothstep(12.,22.,surfaceP.y));totalEmissiveRadiance+=vec3(1.,.13,.008)*ember*2.4;`);};mat.customProgramCacheKey=()=> 'volcanic-fissures';}}else if(old.name==='timber'){mat=surface(old,art.textures.bark,art.textures['bark-normal'],.18);mat.color.setHex(0xc5bfa9);}else if(old.name==='foliage'){mat=old.clone();mat.color.setHex(c.kind==='swamp'?0x697d4d:0x668451);mat.roughness=.9;}materialCache.set(key,mat);}m.material=materialCache.get(key);});return o;}
 function place(name,s,lateral,scale=1,y=0,rot=0,dyn=false){const o=clone(name),a=course.at(s,lateral);o.position.copy(a.p);o.position.y=y;if(Array.isArray(scale))o.scale.set(...scale);else o.scale.setScalar(scale);o.rotation.y=a.heading+rot;(dyn?dynamic:chunks[Math.floor((((s/course.length)%1+1)%1)*12)]).add(o);return o;}

 if(c.kind==='harbour'||c.kind==='sluice')for(let s=0;s<course.length;s+=36){
  for(const side of [-1,1]){if(c.kind==='sluice'&&Math.floor(s/36)%5===4)continue;place('quay',s,side*(c.width+23),[1,c.kind==='sluice'?1.4:1,1],c.kind==='sluice'?-4.9:-3.5,side===1?0:Math.PI);}
 }
 const rockStep=c.kind==='harbour'||c.kind==='sluice'?38:23;
 for(let s=0;s<course.length;s+=rockStep){for(const side of [-1,1]){if(c.kind==='ocean'&&(side===1||random()<.6))continue;const swamp=c.kind==='swamp',harbour=c.kind==='harbour'||c.kind==='sluice';const offset=side*(c.width+14+random()*9);const scale=swamp?[1.8,.22,1.5]:harbour?[1.8,.35,1.5]:[2+random(),(c.kind==='gorge'?2.8:c.kind==='volcano'?.6:1.1)+random()*(c.kind==='volcano'?.8:1.7),1.8+random()];place('rock',s,offset,scale,-4,random()*6.28);if(swamp){for(let j=0;j<4;j++)place('mangrove',s+j*6,offset+side*(random()*35),1.1+random()*1.1,-.9,random()*6.28);}else if(c.kind==='harbour'&&Math.floor(s/rockStep)%3===0)place('crane',s,side*(c.width+24),1,-1,Math.PI*.5);else if(c.kind==='ocean'&&random()>.65)place('rock',s,offset+side*45,[2,4.5,2.5],-6,random()*6.28);}}
 // A distant island ridge anchors the horizon. It never collides with the racing corridor.
 for(let i=0;i<14;i++){const a=i/14*Math.PI*2,o=clone('rock');o.scale.set(17+random()*10,3+random()*3,14+random()*9);o.position.set(Math.cos(a)*760,-38,Math.sin(a)*760);o.rotation.y=a;root.add(o);}
 if(c.kind==='volcano'){const lava=new THREE.MeshStandardMaterial({color:0xfd6b20,emissive:0xff3808,emissiveIntensity:2.5,roughness:.9});const mountain=new THREE.Mesh(new THREE.CylinderGeometry(38,150,150,48,8,true),surface(new THREE.MeshStandardMaterial({color:0xaaa099,roughness:1}),art.textures.basalt,art.textures['basalt-normal'],.06));mountain.position.set(0,72,0);chunks[0].add(mountain);const crater=new THREE.Mesh(new THREE.TorusGeometry(38,4,8,48),lava);crater.rotation.x=Math.PI/2;crater.position.y=147;chunks[0].add(crater);const glow=new THREE.Mesh(new THREE.CircleGeometry(36,48),lava);glow.rotation.x=-Math.PI/2;glow.position.y=144;chunks[0].add(glow);}
 const landmarks=c.kind==='harbour'?[.1,.55]:c.kind==='sluice'?[.14,.37,.61,.83]:[];for(const u of landmarks){const o=place('gate',course.length*u,0,[c.width/17,1.05,1],-1,0);const label=textPlane(u===landmarks[0]?'TIDEBREAK / ATLANTIC RUN':'MERIDIAN AUTHORITY',29,3);label.position.set(0,23,5.1);o.add(label);}
 if(c.kind==='ocean'||c.kind==='harbour')place('lighthouse',course.length*.22,c.width+20,1.5,3);
 if(c.kind==='gorge'){for(const u of [.2,.57,.8]){const a=course.at(course.length*u),arch=clone('rock');arch.position.copy(a.p);arch.position.y=39;arch.rotation.z=Math.PI/2;arch.rotation.y=a.heading;arch.scale.set(1.3,3.5,1.7);chunks[Math.floor(u*12)].add(arch);}}

 // Race edge markers and floating chevrons provide a legible route at full speed.
 const edgeGeo=new THREE.CylinderGeometry(.65,.95,1.6,8),edgeMat=new THREE.MeshStandardMaterial({color:0xff774a,roughness:.5});const arrowMat=new THREE.MeshBasicMaterial({color:0x6ce8d6,transparent:true,opacity:.7,side:THREE.DoubleSide});const arrowShape=new THREE.Shape();arrowShape.moveTo(-2,-1);arrowShape.lineTo(0,2);arrowShape.lineTo(2,-1);arrowShape.lineTo(0,0);arrowShape.closePath();const arrowGeo=new THREE.ShapeGeometry(arrowShape);arrowGeo.rotateX(Math.PI/2);
 for(let s=0;s<course.length;s+=22){for(const side of [-1,1]){const a=course.at(s,side*(c.width-2)),o=new THREE.Mesh(edgeGeo,edgeMat);o.position.copy(a.p);o.position.y=.25;chunks[Math.floor(s/course.length*12)].add(o);}if(Math.floor(s/22)%4===1){const a=course.at(s),o=new THREE.Mesh(arrowGeo,arrowMat);o.position.copy(a.p);o.position.y=.25;o.rotation.y=a.heading;chunks[Math.floor(s/course.length*12)].add(o);}}
 const pickups=[];for(let i=0;i<16;i++){const s=(.04+i*.057)*course.length,offset=c.kind==='swamp'?Math.sin(i*1.7)*8:Math.sin(i*2)*10;const o=place('buoy',s,offset,.65,0,0,true);pickups.push({s,offset,obj:o,collected:false,signal:c.kind==='swamp'});}
 const ramps=[];for(const u of (c.kind==='gorge'?[.18,.42,.69]:c.kind==='ocean'?[.32,.7]:[.38,.73])){const s=u*course.length;const o=place('ramp',s,0,1,-.35,0,true);ramps.push({s,obj:o,used:false});}
 const surges=[];if(c.kind==='sluice'){for(const [i,u] of [.14,.37,.61,.83].entries()){const s=u*course.length,a=course.at(s);const sign=textPlane('SURGE WINDOW',22,3,'#60dbd5');sign.position.copy(a.p);sign.position.y=16;sign.rotation.y=a.heading+Math.PI;dynamic.add(sign);const bar=new THREE.Mesh(new THREE.BoxGeometry(c.width*1.65,.25,.4),new THREE.MeshBasicMaterial({color:0x60dbd5}));bar.position.copy(a.p);bar.position.y=13;bar.rotation.y=a.heading;dynamic.add(bar);surges.push({s,phase:i*1.7,bar,used:false,open:true});}}
 const finish=course.at(0),banner=textPlane('START / FINISH',30,3);banner.position.copy(finish.p);banner.position.y=15;banner.rotation.y=finish.heading+Math.PI;dynamic.add(banner);
 for(const chunk of chunks){if(chunk.children.length)root.add(bakeStatic(chunk));}
 return{root,pickups,ramps,surges,dispose(){
 const sharedGeometry=new Set(),sharedMaterials=new Set(),sharedTextures=new Set(Object.values(art.textures));Object.values(art.prototypes).forEach(p=>p.traverse(o=>{if(o.isMesh){sharedGeometry.add(o.geometry);sharedMaterials.add(o.material);}}));
 const geometries=new Set(),materials=new Set();root.traverse(o=>{if(o.isMesh){geometries.add(o.geometry);materials.add(o.material);}});
 for(const g of geometries)if(!sharedGeometry.has(g))g.dispose();for(const m of materials)if(!sharedMaterials.has(m)){if(m.map&&!sharedTextures.has(m.map))m.map.dispose();m.dispose();}
 },reset(){for(const p of pickups){p.collected=false;p.obj.visible=true;}ramps.forEach(r=>r.used=false);surges.forEach(s=>s.used=false);},update(t){for(const p of pickups)if(!p.collected)p.obj.position.y=Math.sin(t*2+p.s)*.12;for(const gate of surges){gate.open=(t+gate.phase)%10<7;gate.bar.material.color.setHex(gate.open?0x60efcd:0xff653f);gate.bar.scale.y=gate.open?1:2;}}};
}
