// Sustained live-release profiling. Only menu actions and keyboard/touch drive the game.
// An isolated save fixture opens later territories; it is not earned-unlock evidence.
import puppeteer from '../../../404-game-recipe/node_modules/puppeteer/lib/puppeteer/puppeteer.js';
import fs from 'node:fs';import assert from 'node:assert/strict';
const url=process.env.GAME_URL||'https://adams4587000.github.io/tidebreak/',out=process.env.EVIDENCE_DIR||'evidence/pages-performance/sustained';fs.mkdirSync(out,{recursive:true});
const browser=await puppeteer.launch({headless:true,args:['--no-sandbox']}),report={url,fixture:'Isolated browser career save opens later territories only; no simulation state is injected.',runs:[],errors:[]};
const stats=frames=>{const a=frames.map(f=>f.dt).sort((a,b)=>a-b),q=p=>a[Math.min(a.length-1,Math.floor(a.length*p))]||0;return{frames:a.length,medianFps:1000/q(.5),averageFps:a.length*1000/a.reduce((s,v)=>s+v,0),p95Ms:q(.95),p99Ms:q(.99),maxMs:q(1),over50ms:a.filter(x=>x>50.1).length,over100ms:a.filter(x=>x>100).length,peakDraws:Math.max(...frames.map(f=>f.draws)),peakTris:Math.max(...frames.map(f=>f.tris)),minRenderScale:Math.min(...frames.map(f=>f.scale))};};
try{for(const mobile of process.env.PROFILE==='phone'?[true]:process.env.PROFILE==='desktop'?[false]:[false,true]){
 const page=await browser.newPage();await page.setViewport(mobile?{width:390,height:844,isMobile:true,hasTouch:true,deviceScaleFactor:3}:{width:1440,height:900,deviceScaleFactor:1});const cdp=await page.createCDPSession();await cdp.send('Emulation.setCPUThrottlingRate',{rate:mobile?4:1});
 page.on('pageerror',e=>report.errors.push(e.message));page.on('console',e=>{if(e.type()==='error')report.errors.push(e.text());});page.on('response',r=>{if(r.status()>=400)report.errors.push(`${r.status()} ${r.url()}`);});
 await page.evaluateOnNewDocument(()=>{window.observedFrames=[];window.observedTasks=[];new PerformanceObserver(list=>window.observedTasks.push(...list.getEntries().map(e=>({start:e.startTime,duration:e.duration})))).observe({type:'longtask',buffered:true});let before=0;function sample(t){const g=window.__GAME__;if(before&&g)window.observedFrames.push({t,dt:t-before,state:g.state,elapsed:g.elapsed,draws:g.draws,tris:g.tris,scale:g.renderScale});before=t;requestAnimationFrame(sample);}requestAnimationFrame(sample);});
 await page.goto(url);await page.waitForFunction('window.__READY__',{timeout:60000});
 await page.evaluate(async()=>{const {SAVE_KEY,loadSave}=await import('./campaign.js');const save=loadSave();save.cleared=Array(6).fill(true);localStorage.setItem(SAVE_KEY,JSON.stringify(save));});await page.reload();await page.waitForFunction('window.__READY__',{timeout:60000});await page.evaluate(async()=>{const {CHAPTERS}=await import('./campaign.js'),{makeCourse}=await import('./course.js');window.observedCourses=CHAPTERS.map(makeCourse);});
 const click=async s=>{if(mobile){await page.$eval(s,e=>e.scrollIntoView({behavior:'instant',block:'center',inline:'center'}));await page.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));await page.tap(s);}else await page.click(s);};await click('#enterdock');const held=new Set();let touches=[];
 const key=async(k,on)=>{if(on&&!held.has(k)){await page.keyboard.down(k);held.add(k);}else if(!on&&held.has(k)){await page.keyboard.up(k);held.delete(k);}};
 async function touch(points){const added=points.some(p=>!touches.some(x=>x.id===p.id)),removed=touches.some(p=>!points.some(x=>x.id===p.id));await cdp.send('Input.dispatchTouchEvent',{type:added?'touchStart':removed?'touchEnd':'touchMove',touchPoints:points});touches=points;}
 for(const arena of process.env.ARENAS?process.env.ARENAS.split(',').map(Number):[0,1,2,3,4,5]){
  await click('#arenasb');await click(`[data-course="${arena}"]`);if(process.env.TRACE)await page.tracing.start({path:`/tmp/tidebreak-pages-${arena}.trace.json`,categories:['devtools.timeline','v8','disabled-by-default-v8.cpu_profiler']});await click('#startb');await page.waitForFunction('window.__GAME__.state==="countdown"');const startAt=await page.evaluate(()=>performance.now());console.log('START',mobile?'phone':'desktop',arena);
  const controls=mobile?await page.evaluate(()=>Object.fromEntries(['stick','boostb','brakeb'].map(id=>{const r=document.getElementById(id).getBoundingClientRect();return[id,{x:r.x+r.width/2,y:r.y+r.height/2,w:r.width}];}))):null;
  await page.waitForFunction('window.__GAME__.state==="race"');let lastFire=0,shielded=false,t;const deadline=Date.now()+90000;
  while(Date.now()<deadline){
   t=await page.evaluate(()=>{const t=window.__GAME__,s=t.progress*t.courseLength,c=window.observedCourses[t.chapter],pick=t.nextPickup;let offset=pick&&pick.s-s<160?pick.offset:0;for(const o of t.obstacleAhead)if(!o.kind.startsWith('RAMP')&&o.s-s<110&&Math.abs(offset-o.offset)<o.radius+4)offset=o.offset+(offset>=o.offset?1:-1)*(o.radius+6);for(const r of t.rampsAhead)if(r.s-s<90)offset=0;if(t.lethalAhead?.distance<100)offset=t.lethalAhead.offset>0?-6:6;const p=c.at(s+Math.max(20,t.speed*.58),offset).p;return{...t,target:Math.atan2(p.x-t.pos[0],p.z-t.pos[1])};});
   assert.equal(t.state,'race');assert.equal(t.chapter,arena,'touch selects the intended territory');assert.equal(t.previewUnlocks,false);if(t.elapsed>=30)break;
   const d=Math.atan2(Math.sin(t.target-t.heading),Math.cos(t.target-t.heading)),boost=Math.abs(d)<.28&&t.boost>4,brake=Math.abs(d)>.65&&t.speed>29;
   if(mobile){const c=controls.stick,points=[{id:0,x:c.x-Math.max(-1,Math.min(1,d*3))*c.w*.36,y:c.y}];if(boost){const b=controls.boostb;points.push({id:1,x:b.x,y:b.y});}if(brake){const b=controls.brakeb;points.push({id:2,x:b.x,y:b.y});}await touch(points);}else{await key('ArrowLeft',d>.025);await key('ArrowRight',d<-.025);await key('Space',boost);await key('ArrowDown',brake);}
   if(t.elapsed>4&&t.elapsed-lastFire>7&&t.weapons.ammo>0){if(mobile){await touch([]);await click('#fireb');}else await page.keyboard.press('KeyF');lastFire=t.elapsed;}
   if(t.elapsed>10&&!shielded){if(mobile){await touch([]);await click('#shieldb');}else await page.keyboard.press('KeyE');shielded=true;}
   await new Promise(resolve=>setTimeout(resolve,70));
  }
  assert.ok(t.elapsed>=30);if(mobile)await touch([]);for(const k of [...held])await key(k,false);
  const frames=await page.evaluate(start=>window.observedFrames.filter(f=>f.t>=start),startAt),run={mobile,cpuSlowdown:mobile?4:1,arena:t.arena,elapsed:t.elapsed,progress:t.progress,pickups:t.pickups,jumps:t.jumps,shots:t.weapons.shots,countdown:stats(frames.filter(f=>f.state==='countdown')),launch:stats(frames.filter(f=>f.state==='race'&&f.elapsed<3)),racing:stats(frames.filter(f=>f.state==='race'&&f.elapsed>=3))};
  run.longTasks=await page.evaluate(start=>window.observedTasks.filter(t=>t.start>=start),startAt);if(process.env.TRACE)await page.tracing.stop();report.runs.push(run);fs.writeFileSync(`${out}/${mobile?'phone':'desktop'}-${arena}-frames.json`,JSON.stringify(frames));console.log(JSON.stringify(run));fs.writeFileSync(out+'/summary.json',JSON.stringify(report,null,2));await page.screenshot({path:`${out}/${mobile?'phone':'desktop'}-${arena}.png`});await click('#pauseb');await click('#exitb');
 }
 await page.close();
}assert.deepEqual(report.errors,[]);for(const r of report.runs){assert.ok(r.racing.averageFps>50);assert.ok(r.racing.p95Ms<34);assert.ok(r.racing.peakDraws<900);assert.ok(r.racing.peakTris<1500000);}report.passed=true;}catch(e){report.failure=e.stack;process.exitCode=1;console.error(e);}finally{fs.writeFileSync(out+'/summary.json',JSON.stringify(report,null,2));await browser.close();}
